import 'dart:math';
import '../models/move.dart';

/// Static table of the moves available for each of the 11 types in
/// the game (30 per type, in 5 power tiers), plus a shared pool of
/// 50 'universal' moves any Wildkin can learn regardless of type.
///
/// Tiers unlock at level 1 / 15 / 35 / 55 / 80. A move can carry at
/// most one special mechanic: weatherAffinity (bonus damage when the
/// REAL weather at battle time matches), timeAffinity (bonus at real
/// night/dawn), inflictsStatus (chance to apply a status effect — see
/// StatusEffect), or scalesWithTargetWeight (more damage the heavier
/// the target is — see WildkinPhysique).
///
/// All move names are original — checked against a blocklist of
/// existing games' move names at generation time.
class MovePool {
  static const Map<String, List<Move>> _byType = {
    'fire': [
      Move(name: 'Flare Spiral', type: 'fire', category: MoveCategory.special, power: 40, accuracy: 96, maxPp: 31, tier: 1, minLevel: 1),
      Move(name: 'Flare Burst', type: 'fire', category: MoveCategory.physical, power: 31, accuracy: 95, maxPp: 33, tier: 1, minLevel: 1),
      Move(name: 'Smolder Burst', type: 'fire', category: MoveCategory.special, power: 33, accuracy: 97, maxPp: 34, tier: 1, minLevel: 1),
      Move(name: 'Cinder Flurry', type: 'fire', category: MoveCategory.physical, power: 31, accuracy: 99, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Kindling Veil', type: 'fire', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 31, tier: 1, minLevel: 1),
      Move(name: 'Pyre Lash', type: 'fire', category: MoveCategory.physical, power: 43, accuracy: 95, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Cinder Burst', type: 'fire', category: MoveCategory.special, power: 52, accuracy: 98, maxPp: 23, tier: 2, minLevel: 15, weatherAffinity: 'fire', weatherBonusPct: 20),
      Move(name: 'Ashfall Lash', type: 'fire', category: MoveCategory.physical, power: 57, accuracy: 100, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Blaze Veil', type: 'fire', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Ashfall Wave', type: 'fire', category: MoveCategory.physical, power: 57, accuracy: 90, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Ashfall Surge', type: 'fire', category: MoveCategory.special, power: 59, accuracy: 96, maxPp: 21, tier: 2, minLevel: 15),
      Move(name: 'Blaze Lash', type: 'fire', category: MoveCategory.physical, power: 59, accuracy: 98, maxPp: 25, tier: 2, minLevel: 15, weatherAffinity: 'fire', weatherBonusPct: 20),
      Move(name: 'Pyre Veil', type: 'fire', category: MoveCategory.status, power: 0, accuracy: 93, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Pyre Storm', type: 'fire', category: MoveCategory.physical, power: 71, accuracy: 91, maxPp: 18, tier: 3, minLevel: 35),
      Move(name: 'Ashfall Spiral', type: 'fire', category: MoveCategory.special, power: 83, accuracy: 95, maxPp: 18, tier: 3, minLevel: 35),
      Move(name: 'Flare Veil', type: 'fire', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 17, tier: 3, minLevel: 35, weatherAffinity: 'fire', weatherBonusPct: 20),
      Move(name: 'Flare Wave', type: 'fire', category: MoveCategory.special, power: 77, accuracy: 87, maxPp: 19, tier: 3, minLevel: 35, weatherAffinity: 'fire', weatherBonusPct: 20),
      Move(name: 'Smolder Spiral', type: 'fire', category: MoveCategory.physical, power: 80, accuracy: 99, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Ashfall Storm', type: 'fire', category: MoveCategory.special, power: 92, accuracy: 83, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Magma Bloom', type: 'fire', category: MoveCategory.physical, power: 100, accuracy: 84, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Magma Lash', type: 'fire', category: MoveCategory.special, power: 92, accuracy: 90, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Scorch Burst', type: 'fire', category: MoveCategory.physical, power: 105, accuracy: 94, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Magma Spiral', type: 'fire', category: MoveCategory.special, power: 98, accuracy: 95, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Smolder Storm', type: 'fire', category: MoveCategory.physical, power: 91, accuracy: 89, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Wildfire Lash', type: 'fire', category: MoveCategory.special, power: 124, accuracy: 79, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Flare Flurry', type: 'fire', category: MoveCategory.physical, power: 121, accuracy: 70, maxPp: 8, tier: 5, minLevel: 80),
      Move(name: 'Wildfire Surge', type: 'fire', category: MoveCategory.special, power: 129, accuracy: 73, maxPp: 8, tier: 5, minLevel: 80, weatherAffinity: 'fire', weatherBonusPct: 20),
      Move(name: 'Scorch Storm', type: 'fire', category: MoveCategory.physical, power: 114, accuracy: 77, maxPp: 8, tier: 5, minLevel: 80),
      Move(name: 'Wildfire Bloom', type: 'fire', category: MoveCategory.special, power: 125, accuracy: 72, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Magma Surge', type: 'fire', category: MoveCategory.physical, power: 127, accuracy: 78, maxPp: 6, tier: 5, minLevel: 80),
    ],
    'water': [
      Move(name: 'Deluge Drench', type: 'water', category: MoveCategory.special, power: 38, accuracy: 100, maxPp: 31, tier: 1, minLevel: 1),
      Move(name: 'Torrent Swell', type: 'water', category: MoveCategory.physical, power: 41, accuracy: 100, maxPp: 31, tier: 1, minLevel: 1),
      Move(name: 'Tide Flow', type: 'water', category: MoveCategory.special, power: 37, accuracy: 96, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Current Veil', type: 'water', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Cascade Crash', type: 'water', category: MoveCategory.special, power: 37, accuracy: 95, maxPp: 32, tier: 1, minLevel: 1),
      Move(name: 'Torrent Lash', type: 'water', category: MoveCategory.physical, power: 35, accuracy: 97, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Torrent Spiral', type: 'water', category: MoveCategory.special, power: 50, accuracy: 92, maxPp: 23, tier: 2, minLevel: 15),
      Move(name: 'Undertow Churn', type: 'water', category: MoveCategory.physical, power: 60, accuracy: 92, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Torrent Flow', type: 'water', category: MoveCategory.special, power: 51, accuracy: 97, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Deluge Spiral', type: 'water', category: MoveCategory.physical, power: 62, accuracy: 96, maxPp: 23, tier: 2, minLevel: 15),
      Move(name: 'Wellspring Flow', type: 'water', category: MoveCategory.special, power: 65, accuracy: 100, maxPp: 23, tier: 2, minLevel: 15, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Cascade Drench', type: 'water', category: MoveCategory.physical, power: 56, accuracy: 97, maxPp: 21, tier: 2, minLevel: 15, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Riptide Ripple', type: 'water', category: MoveCategory.special, power: 73, accuracy: 85, maxPp: 19, tier: 3, minLevel: 35, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Brine Lash', type: 'water', category: MoveCategory.physical, power: 81, accuracy: 85, maxPp: 15, tier: 3, minLevel: 35),
      Move(name: 'Brine Spiral', type: 'water', category: MoveCategory.special, power: 82, accuracy: 89, maxPp: 20, tier: 3, minLevel: 35, inflictsStatus: 'waterlogged', statusChancePct: 25),
      Move(name: 'Tide Lash', type: 'water', category: MoveCategory.physical, power: 85, accuracy: 88, maxPp: 15, tier: 3, minLevel: 35),
      Move(name: 'Cascade Ripple', type: 'water', category: MoveCategory.special, power: 84, accuracy: 100, maxPp: 18, tier: 3, minLevel: 35, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Riptide Drench', type: 'water', category: MoveCategory.physical, power: 73, accuracy: 95, maxPp: 20, tier: 3, minLevel: 35, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Undertow Surge', type: 'water', category: MoveCategory.special, power: 90, accuracy: 86, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Tide Spiral', type: 'water', category: MoveCategory.physical, power: 90, accuracy: 89, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Brine Drench', type: 'water', category: MoveCategory.special, power: 98, accuracy: 91, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Maelstrom Lash', type: 'water', category: MoveCategory.physical, power: 97, accuracy: 90, maxPp: 15, tier: 4, minLevel: 55, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Tide Crash', type: 'water', category: MoveCategory.special, power: 97, accuracy: 92, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Deluge Veil', type: 'water', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Wellspring Lash', type: 'water', category: MoveCategory.special, power: 110, accuracy: 78, maxPp: 8, tier: 5, minLevel: 80, inflictsStatus: 'waterlogged', statusChancePct: 25),
      Move(name: 'Maelstrom Swell', type: 'water', category: MoveCategory.physical, power: 121, accuracy: 81, maxPp: 5, tier: 5, minLevel: 80, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Tide Veil', type: 'water', category: MoveCategory.status, power: 0, accuracy: 81, maxPp: 7, tier: 5, minLevel: 80, weatherAffinity: 'water', weatherBonusPct: 20),
      Move(name: 'Wellspring Swell', type: 'water', category: MoveCategory.physical, power: 125, accuracy: 90, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Current Flow', type: 'water', category: MoveCategory.special, power: 112, accuracy: 73, maxPp: 8, tier: 5, minLevel: 80),
      Move(name: 'Undertow Swell', type: 'water', category: MoveCategory.physical, power: 116, accuracy: 85, maxPp: 6, tier: 5, minLevel: 80),
    ],
    'electric': [
      Move(name: 'Arc Flicker', type: 'electric', category: MoveCategory.special, power: 40, accuracy: 95, maxPp: 31, tier: 1, minLevel: 1),
      Move(name: 'Coil Blitz', type: 'electric', category: MoveCategory.physical, power: 44, accuracy: 98, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Arc Blitz', type: 'electric', category: MoveCategory.special, power: 35, accuracy: 96, maxPp: 27, tier: 1, minLevel: 1),
      Move(name: 'Volt Flicker', type: 'electric', category: MoveCategory.physical, power: 30, accuracy: 96, maxPp: 34, tier: 1, minLevel: 1),
      Move(name: 'Arc Surge', type: 'electric', category: MoveCategory.special, power: 44, accuracy: 100, maxPp: 27, tier: 1, minLevel: 1),
      Move(name: 'Jolt Flicker', type: 'electric', category: MoveCategory.physical, power: 45, accuracy: 100, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Amp Flicker', type: 'electric', category: MoveCategory.special, power: 54, accuracy: 98, maxPp: 24, tier: 2, minLevel: 15, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Volt Strike', type: 'electric', category: MoveCategory.physical, power: 53, accuracy: 98, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Jolt Storm', type: 'electric', category: MoveCategory.special, power: 63, accuracy: 93, maxPp: 21, tier: 2, minLevel: 15, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Jolt Blitz', type: 'electric', category: MoveCategory.physical, power: 59, accuracy: 98, maxPp: 21, tier: 2, minLevel: 15),
      Move(name: 'Circuit Lash', type: 'electric', category: MoveCategory.special, power: 60, accuracy: 94, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Jolt Lash', type: 'electric', category: MoveCategory.physical, power: 54, accuracy: 90, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Volt Pulse', type: 'electric', category: MoveCategory.special, power: 84, accuracy: 98, maxPp: 19, tier: 3, minLevel: 35, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Jolt Surge', type: 'electric', category: MoveCategory.physical, power: 70, accuracy: 99, maxPp: 16, tier: 3, minLevel: 35),
      Move(name: 'Volt Surge', type: 'electric', category: MoveCategory.special, power: 74, accuracy: 90, maxPp: 16, tier: 3, minLevel: 35),
      Move(name: 'Flux Blitz', type: 'electric', category: MoveCategory.physical, power: 73, accuracy: 86, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Amp Blitz', type: 'electric', category: MoveCategory.special, power: 85, accuracy: 88, maxPp: 19, tier: 3, minLevel: 35, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Coil Lash', type: 'electric', category: MoveCategory.physical, power: 78, accuracy: 86, maxPp: 15, tier: 3, minLevel: 35),
      Move(name: 'Flux Surge', type: 'electric', category: MoveCategory.special, power: 90, accuracy: 82, maxPp: 13, tier: 4, minLevel: 55, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Coil Pulse', type: 'electric', category: MoveCategory.physical, power: 98, accuracy: 94, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Charge Burst', type: 'electric', category: MoveCategory.special, power: 105, accuracy: 87, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Volt Lash', type: 'electric', category: MoveCategory.physical, power: 98, accuracy: 86, maxPp: 13, tier: 4, minLevel: 55, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Static Crackle', type: 'electric', category: MoveCategory.special, power: 102, accuracy: 94, maxPp: 12, tier: 4, minLevel: 55, weatherAffinity: 'electric', weatherBonusPct: 20),
      Move(name: 'Amp Storm', type: 'electric', category: MoveCategory.physical, power: 103, accuracy: 82, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Coil Discharge', type: 'electric', category: MoveCategory.special, power: 113, accuracy: 74, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Fuse Burst', type: 'electric', category: MoveCategory.physical, power: 121, accuracy: 74, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Amp Crackle', type: 'electric', category: MoveCategory.special, power: 124, accuracy: 77, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Charge Surge', type: 'electric', category: MoveCategory.physical, power: 122, accuracy: 85, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Jolt Discharge', type: 'electric', category: MoveCategory.special, power: 117, accuracy: 75, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Circuit Strike', type: 'electric', category: MoveCategory.physical, power: 126, accuracy: 82, maxPp: 7, tier: 5, minLevel: 80),
    ],
    'grass': [
      Move(name: 'Vine Burst', type: 'grass', category: MoveCategory.special, power: 41, accuracy: 97, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Bloom Sprawl', type: 'grass', category: MoveCategory.physical, power: 41, accuracy: 95, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Sap Drain', type: 'grass', category: MoveCategory.special, power: 44, accuracy: 98, maxPp: 25, tier: 1, minLevel: 1),
      Move(name: 'Bark Drain', type: 'grass', category: MoveCategory.physical, power: 42, accuracy: 97, maxPp: 33, tier: 1, minLevel: 1),
      Move(name: 'Thorn Lash', type: 'grass', category: MoveCategory.special, power: 39, accuracy: 99, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Bramble Coil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Fern Snap', type: 'grass', category: MoveCategory.special, power: 52, accuracy: 94, maxPp: 22, tier: 2, minLevel: 15, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Thorn Coil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 97, maxPp: 23, tier: 2, minLevel: 15),
      Move(name: 'Sap Veil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 21, tier: 2, minLevel: 15),
      Move(name: 'Moss Burst', type: 'grass', category: MoveCategory.physical, power: 65, accuracy: 95, maxPp: 20, tier: 2, minLevel: 15, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Fern Bind', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 96, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Bramble Lash', type: 'grass', category: MoveCategory.physical, power: 52, accuracy: 94, maxPp: 20, tier: 2, minLevel: 15),
      Move(name: 'Vine Bind', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 92, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Pollen Sprawl', type: 'grass', category: MoveCategory.physical, power: 84, accuracy: 85, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Thorn Bind', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 98, maxPp: 19, tier: 3, minLevel: 35, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Moss Coil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 95, maxPp: 17, tier: 3, minLevel: 35, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Moss Bind', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 99, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Bark Sprawl', type: 'grass', category: MoveCategory.physical, power: 79, accuracy: 99, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Sap Bind', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 96, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Sap Lash', type: 'grass', category: MoveCategory.physical, power: 91, accuracy: 80, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Moss Lash', type: 'grass', category: MoveCategory.special, power: 96, accuracy: 95, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Root Drain', type: 'grass', category: MoveCategory.physical, power: 93, accuracy: 93, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Vine Veil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 94, maxPp: 15, tier: 4, minLevel: 55, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Bramble Sprawl', type: 'grass', category: MoveCategory.physical, power: 100, accuracy: 86, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Moss Sprawl', type: 'grass', category: MoveCategory.special, power: 114, accuracy: 82, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Moss Veil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 75, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Thorn Drain', type: 'grass', category: MoveCategory.special, power: 118, accuracy: 83, maxPp: 6, tier: 5, minLevel: 80, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Moss Spiral', type: 'grass', category: MoveCategory.physical, power: 126, accuracy: 79, maxPp: 9, tier: 5, minLevel: 80, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Fern Coil', type: 'grass', category: MoveCategory.status, power: 0, accuracy: 89, maxPp: 6, tier: 5, minLevel: 80, weatherAffinity: 'grass', weatherBonusPct: 20),
      Move(name: 'Bloom Weave', type: 'grass', category: MoveCategory.physical, power: 110, accuracy: 78, maxPp: 7, tier: 5, minLevel: 80),
    ],
    'ice': [
      Move(name: 'Crystal Spiral', type: 'ice', category: MoveCategory.special, power: 40, accuracy: 96, maxPp: 25, tier: 1, minLevel: 1),
      Move(name: 'Rime Burst', type: 'ice', category: MoveCategory.physical, power: 39, accuracy: 96, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Crystal Squall', type: 'ice', category: MoveCategory.special, power: 35, accuracy: 95, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Hoarfrost Storm', type: 'ice', category: MoveCategory.physical, power: 42, accuracy: 95, maxPp: 32, tier: 1, minLevel: 1),
      Move(name: 'Sleet Drift', type: 'ice', category: MoveCategory.special, power: 38, accuracy: 99, maxPp: 35, tier: 1, minLevel: 1),
      Move(name: 'Frost Squall', type: 'ice', category: MoveCategory.physical, power: 36, accuracy: 96, maxPp: 33, tier: 1, minLevel: 1),
      Move(name: 'Glaze Squall', type: 'ice', category: MoveCategory.special, power: 50, accuracy: 91, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Permafrost Shard', type: 'ice', category: MoveCategory.physical, power: 54, accuracy: 96, maxPp: 24, tier: 2, minLevel: 15, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Hoarfrost Burst', type: 'ice', category: MoveCategory.special, power: 59, accuracy: 94, maxPp: 25, tier: 2, minLevel: 15, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Icicle Spike', type: 'ice', category: MoveCategory.physical, power: 62, accuracy: 95, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Tundra Shard', type: 'ice', category: MoveCategory.special, power: 54, accuracy: 94, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Hoarfrost Spiral', type: 'ice', category: MoveCategory.physical, power: 54, accuracy: 90, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Sleet Squall', type: 'ice', category: MoveCategory.special, power: 83, accuracy: 89, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Glaze Burst', type: 'ice', category: MoveCategory.physical, power: 70, accuracy: 92, maxPp: 15, tier: 3, minLevel: 35, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Icicle Burst', type: 'ice', category: MoveCategory.special, power: 81, accuracy: 88, maxPp: 18, tier: 3, minLevel: 35),
      Move(name: 'Hoarfrost Lash', type: 'ice', category: MoveCategory.physical, power: 71, accuracy: 85, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Tundra Burst', type: 'ice', category: MoveCategory.special, power: 77, accuracy: 100, maxPp: 17, tier: 3, minLevel: 35, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Glaze Drift', type: 'ice', category: MoveCategory.physical, power: 72, accuracy: 87, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Icicle Shard', type: 'ice', category: MoveCategory.special, power: 98, accuracy: 82, maxPp: 12, tier: 4, minLevel: 55, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Glacial Spike', type: 'ice', category: MoveCategory.physical, power: 97, accuracy: 94, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Crystal Storm', type: 'ice', category: MoveCategory.special, power: 92, accuracy: 95, maxPp: 15, tier: 4, minLevel: 55, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Sleet Burst', type: 'ice', category: MoveCategory.physical, power: 96, accuracy: 82, maxPp: 14, tier: 4, minLevel: 55, inflictsStatus: 'chilled', statusChancePct: 25),
      Move(name: 'Rime Drift', type: 'ice', category: MoveCategory.special, power: 99, accuracy: 84, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Permafrost Spike', type: 'ice', category: MoveCategory.physical, power: 105, accuracy: 88, maxPp: 15, tier: 4, minLevel: 55, weatherAffinity: 'ice', weatherBonusPct: 20),
      Move(name: 'Rime Squall', type: 'ice', category: MoveCategory.special, power: 125, accuracy: 79, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Tundra Storm', type: 'ice', category: MoveCategory.physical, power: 124, accuracy: 84, maxPp: 8, tier: 5, minLevel: 80),
      Move(name: 'Crystal Crackle', type: 'ice', category: MoveCategory.special, power: 127, accuracy: 76, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Frost Drift', type: 'ice', category: MoveCategory.physical, power: 125, accuracy: 70, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Icicle Spiral', type: 'ice', category: MoveCategory.special, power: 126, accuracy: 84, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Frost Shard', type: 'ice', category: MoveCategory.physical, power: 116, accuracy: 72, maxPp: 9, tier: 5, minLevel: 80, inflictsStatus: 'chilled', statusChancePct: 25),
    ],
    'poison': [
      Move(name: 'Corrosion Fester', type: 'poison', category: MoveCategory.special, power: 34, accuracy: 99, maxPp: 35, tier: 1, minLevel: 1),
      Move(name: 'Rot Burst', type: 'poison', category: MoveCategory.physical, power: 38, accuracy: 95, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Corrosion Lash', type: 'poison', category: MoveCategory.special, power: 37, accuracy: 98, maxPp: 32, tier: 1, minLevel: 1),
      Move(name: 'Bile Prick', type: 'poison', category: MoveCategory.physical, power: 42, accuracy: 95, maxPp: 27, tier: 1, minLevel: 1),
      Move(name: 'Ooze Burst', type: 'poison', category: MoveCategory.special, power: 30, accuracy: 98, maxPp: 35, tier: 1, minLevel: 1),
      Move(name: 'Rot Prick', type: 'poison', category: MoveCategory.physical, power: 44, accuracy: 98, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Fume Prick', type: 'poison', category: MoveCategory.special, power: 54, accuracy: 96, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Fume Burst', type: 'poison', category: MoveCategory.physical, power: 53, accuracy: 95, maxPp: 20, tier: 2, minLevel: 15, inflictsStatus: 'toxic_film', statusChancePct: 25),
      Move(name: 'Miasma Lash', type: 'poison', category: MoveCategory.special, power: 0, accuracy: 93, maxPp: 25, tier: 2, minLevel: 15, inflictsStatus: 'toxic_film', statusChancePct: 25),
      Move(name: 'Ooze Drip', type: 'poison', category: MoveCategory.physical, power: 52, accuracy: 96, maxPp: 23, tier: 2, minLevel: 15),
      Move(name: 'Toxin Soak', type: 'poison', category: MoveCategory.special, power: 52, accuracy: 95, maxPp: 23, tier: 2, minLevel: 15),
      Move(name: 'Venom Burst', type: 'poison', category: MoveCategory.physical, power: 51, accuracy: 94, maxPp: 20, tier: 2, minLevel: 15, inflictsStatus: 'toxic_film', statusChancePct: 25),
      Move(name: 'Miasma Veil', type: 'poison', category: MoveCategory.status, power: 0, accuracy: 97, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Blight Drip', type: 'poison', category: MoveCategory.physical, power: 80, accuracy: 91, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Fume Spray', type: 'poison', category: MoveCategory.special, power: 83, accuracy: 85, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Rot Veil', type: 'poison', category: MoveCategory.status, power: 0, accuracy: 92, maxPp: 15, tier: 3, minLevel: 35),
      Move(name: 'Rot Cloud', type: 'poison', category: MoveCategory.special, power: 83, accuracy: 99, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Rot Fester', type: 'poison', category: MoveCategory.physical, power: 79, accuracy: 100, maxPp: 15, tier: 3, minLevel: 35),
      Move(name: 'Blight Veil', type: 'poison', category: MoveCategory.status, power: 0, accuracy: 90, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Toxin Veil', type: 'poison', category: MoveCategory.status, power: 0, accuracy: 94, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Blight Soak', type: 'poison', category: MoveCategory.special, power: 98, accuracy: 92, maxPp: 15, tier: 4, minLevel: 55, inflictsStatus: 'toxic_film', statusChancePct: 25),
      Move(name: 'Venom Prick', type: 'poison', category: MoveCategory.physical, power: 102, accuracy: 83, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Corrosion Prick', type: 'poison', category: MoveCategory.special, power: 92, accuracy: 86, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Bile Drip', type: 'poison', category: MoveCategory.physical, power: 105, accuracy: 87, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Ooze Fester', type: 'poison', category: MoveCategory.special, power: 124, accuracy: 83, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Ooze Cloud', type: 'poison', category: MoveCategory.physical, power: 117, accuracy: 72, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Miasma Spray', type: 'poison', category: MoveCategory.special, power: 112, accuracy: 80, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Rot Soak', type: 'poison', category: MoveCategory.physical, power: 128, accuracy: 76, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Toxin Prick', type: 'poison', category: MoveCategory.special, power: 123, accuracy: 82, maxPp: 8, tier: 5, minLevel: 80),
      Move(name: 'Venom Veil', type: 'poison', category: MoveCategory.status, power: 0, accuracy: 87, maxPp: 7, tier: 5, minLevel: 80),
    ],
    'ground': [
      Move(name: 'Silt Strike', type: 'ground', category: MoveCategory.special, power: 31, accuracy: 98, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Canyon Veil', type: 'ground', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 35, tier: 1, minLevel: 1),
      Move(name: 'Dust Shake', type: 'ground', category: MoveCategory.special, power: 36, accuracy: 95, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Bedrock Grind', type: 'ground', category: MoveCategory.physical, power: 37, accuracy: 98, maxPp: 31, tier: 1, minLevel: 1),
      Move(name: 'Pitfall Slam', type: 'ground', category: MoveCategory.special, power: 44, accuracy: 98, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Canyon Strike', type: 'ground', category: MoveCategory.physical, power: 30, accuracy: 96, maxPp: 25, tier: 1, minLevel: 1),
      Move(name: 'Canyon Spiral', type: 'ground', category: MoveCategory.special, power: 63, accuracy: 97, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Sand Wave', type: 'ground', category: MoveCategory.physical, power: 52, accuracy: 96, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Crag Toss', type: 'ground', category: MoveCategory.special, power: 64, accuracy: 93, maxPp: 20, tier: 2, minLevel: 15, weatherAffinity: 'ground', weatherBonusPct: 20),
      Move(name: 'Dust Strike', type: 'ground', category: MoveCategory.physical, power: 53, accuracy: 100, maxPp: 23, tier: 2, minLevel: 15, weatherAffinity: 'ground', weatherBonusPct: 20),
      Move(name: 'Dust Crush', type: 'ground', category: MoveCategory.special, power: 50, accuracy: 92, maxPp: 21, tier: 2, minLevel: 15),
      Move(name: 'Pitfall Wave', type: 'ground', category: MoveCategory.physical, power: 51, accuracy: 100, maxPp: 25, tier: 2, minLevel: 15, weatherAffinity: 'ground', weatherBonusPct: 20),
      Move(name: 'Tremor Toss', type: 'ground', category: MoveCategory.special, power: 78, accuracy: 98, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Crag Crush', type: 'ground', category: MoveCategory.physical, power: 73, accuracy: 87, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Dust Spiral', type: 'ground', category: MoveCategory.special, power: 76, accuracy: 97, maxPp: 17, tier: 3, minLevel: 35, weatherAffinity: 'ground', weatherBonusPct: 20),
      Move(name: 'Silt Spiral', type: 'ground', category: MoveCategory.physical, power: 70, accuracy: 94, maxPp: 18, tier: 3, minLevel: 35, inflictsStatus: 'grounded', statusChancePct: 25),
      Move(name: 'Dust Wave', type: 'ground', category: MoveCategory.special, power: 77, accuracy: 100, maxPp: 19, tier: 3, minLevel: 35, weatherAffinity: 'ground', weatherBonusPct: 20),
      Move(name: 'Canyon Toss', type: 'ground', category: MoveCategory.physical, power: 70, accuracy: 98, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Tremor Slam', type: 'ground', category: MoveCategory.special, power: 91, accuracy: 80, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Rubble Toss', type: 'ground', category: MoveCategory.physical, power: 103, accuracy: 82, maxPp: 12, tier: 4, minLevel: 55, inflictsStatus: 'grounded', statusChancePct: 25),
      Move(name: 'Rubble Wave', type: 'ground', category: MoveCategory.special, power: 97, accuracy: 95, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Rubble Shake', type: 'ground', category: MoveCategory.physical, power: 103, accuracy: 91, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Sand Spiral', type: 'ground', category: MoveCategory.special, power: 90, accuracy: 89, maxPp: 15, tier: 4, minLevel: 55),
      Move(name: 'Clay Grind', type: 'ground', category: MoveCategory.physical, power: 92, accuracy: 86, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Dust Burst', type: 'ground', category: MoveCategory.special, power: 119, accuracy: 76, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Clay Veil', type: 'ground', category: MoveCategory.status, power: 0, accuracy: 84, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Clay Wave', type: 'ground', category: MoveCategory.special, power: 125, accuracy: 89, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Clay Burst', type: 'ground', category: MoveCategory.physical, power: 125, accuracy: 83, maxPp: 10, tier: 5, minLevel: 80, scalesWithTargetWeight: true),
      Move(name: 'Tremor Crush', type: 'ground', category: MoveCategory.special, power: 114, accuracy: 82, maxPp: 5, tier: 5, minLevel: 80, weatherAffinity: 'ground', weatherBonusPct: 20),
      Move(name: 'Silt Slam', type: 'ground', category: MoveCategory.physical, power: 123, accuracy: 71, maxPp: 10, tier: 5, minLevel: 80, inflictsStatus: 'grounded', statusChancePct: 25),
    ],
    'flying': [
      Move(name: 'Zephyr Veil', type: 'flying', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Skybound Swoop', type: 'flying', category: MoveCategory.physical, power: 32, accuracy: 96, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Draft Swoop', type: 'flying', category: MoveCategory.special, power: 36, accuracy: 96, maxPp: 35, tier: 1, minLevel: 1),
      Move(name: 'Windrow Swoop', type: 'flying', category: MoveCategory.physical, power: 44, accuracy: 95, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Zephyr Dive', type: 'flying', category: MoveCategory.special, power: 42, accuracy: 97, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Gale Strike', type: 'flying', category: MoveCategory.physical, power: 44, accuracy: 96, maxPp: 26, tier: 1, minLevel: 1),
      Move(name: 'Squall Glide', type: 'flying', category: MoveCategory.special, power: 50, accuracy: 91, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Thermal Glide', type: 'flying', category: MoveCategory.physical, power: 63, accuracy: 91, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Thermal Strike', type: 'flying', category: MoveCategory.special, power: 56, accuracy: 96, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Tempest Strike', type: 'flying', category: MoveCategory.physical, power: 59, accuracy: 96, maxPp: 20, tier: 2, minLevel: 15),
      Move(name: 'Tempest Glide', type: 'flying', category: MoveCategory.special, power: 65, accuracy: 93, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Thermal Lash', type: 'flying', category: MoveCategory.physical, power: 64, accuracy: 93, maxPp: 22, tier: 2, minLevel: 15),
      Move(name: 'Thermal Burst', type: 'flying', category: MoveCategory.special, power: 85, accuracy: 85, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Windrow Burst', type: 'flying', category: MoveCategory.physical, power: 82, accuracy: 86, maxPp: 18, tier: 3, minLevel: 35),
      Move(name: 'Squall Dive', type: 'flying', category: MoveCategory.special, power: 72, accuracy: 86, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Gale Swoop', type: 'flying', category: MoveCategory.physical, power: 72, accuracy: 95, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Windrow Dive', type: 'flying', category: MoveCategory.special, power: 71, accuracy: 93, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Skybound Lash', type: 'flying', category: MoveCategory.physical, power: 80, accuracy: 93, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Zephyr Whirl', type: 'flying', category: MoveCategory.special, power: 92, accuracy: 80, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Cyclone Spiral', type: 'flying', category: MoveCategory.physical, power: 104, accuracy: 92, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Cyclone Burst', type: 'flying', category: MoveCategory.special, power: 105, accuracy: 84, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Windrow Storm', type: 'flying', category: MoveCategory.physical, power: 99, accuracy: 84, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Cyclone Glide', type: 'flying', category: MoveCategory.special, power: 100, accuracy: 94, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Skybound Glide', type: 'flying', category: MoveCategory.physical, power: 92, accuracy: 86, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Skybound Strike', type: 'flying', category: MoveCategory.special, power: 117, accuracy: 83, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Tempest Veil', type: 'flying', category: MoveCategory.status, power: 0, accuracy: 92, maxPp: 9, tier: 5, minLevel: 80),
      Move(name: 'Gale Glide', type: 'flying', category: MoveCategory.special, power: 123, accuracy: 73, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Windrow Spiral', type: 'flying', category: MoveCategory.physical, power: 112, accuracy: 76, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Tempest Spiral', type: 'flying', category: MoveCategory.special, power: 124, accuracy: 75, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Gale Storm', type: 'flying', category: MoveCategory.physical, power: 124, accuracy: 89, maxPp: 10, tier: 5, minLevel: 80),
    ],
    'psychic': [
      Move(name: 'Whisper Grip', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Insight Grip', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Whisper Veil', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 29, tier: 1, minLevel: 1),
      Move(name: 'Trance Wave', type: 'psychic', category: MoveCategory.physical, power: 36, accuracy: 98, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Mirage Bend', type: 'psychic', category: MoveCategory.special, power: 35, accuracy: 96, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Mind Bend', type: 'psychic', category: MoveCategory.physical, power: 34, accuracy: 97, maxPp: 34, tier: 1, minLevel: 1),
      Move(name: 'Trance Fracture', type: 'psychic', category: MoveCategory.special, power: 56, accuracy: 95, maxPp: 20, tier: 2, minLevel: 15),
      Move(name: 'Aura Veil', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 24, tier: 2, minLevel: 15, timeAffinity: 'dawn', timeBonusPct: 15),
      Move(name: 'Mirage Surge', type: 'psychic', category: MoveCategory.special, power: 64, accuracy: 90, maxPp: 20, tier: 2, minLevel: 15, timeAffinity: 'dawn', timeBonusPct: 15),
      Move(name: 'Reverie Pulse', type: 'psychic', category: MoveCategory.physical, power: 64, accuracy: 95, maxPp: 20, tier: 2, minLevel: 15),
      Move(name: 'Insight Pulse', type: 'psychic', category: MoveCategory.special, power: 57, accuracy: 91, maxPp: 20, tier: 2, minLevel: 15, timeAffinity: 'dawn', timeBonusPct: 15),
      Move(name: 'Aura Wave', type: 'psychic', category: MoveCategory.physical, power: 52, accuracy: 95, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Mirage Pulse', type: 'psychic', category: MoveCategory.special, power: 84, accuracy: 93, maxPp: 20, tier: 3, minLevel: 35),
      Move(name: 'Mind Ripple', type: 'psychic', category: MoveCategory.physical, power: 0, accuracy: 96, maxPp: 16, tier: 3, minLevel: 35, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Mirage Wave', type: 'psychic', category: MoveCategory.special, power: 76, accuracy: 93, maxPp: 15, tier: 3, minLevel: 35),
      Move(name: 'Psyche Grip', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 90, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Mind Spiral', type: 'psychic', category: MoveCategory.special, power: 81, accuracy: 90, maxPp: 19, tier: 3, minLevel: 35, timeAffinity: 'dawn', timeBonusPct: 15),
      Move(name: 'Mirage Grip', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Trance Ripple', type: 'psychic', category: MoveCategory.special, power: 103, accuracy: 83, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Mirage Burst', type: 'psychic', category: MoveCategory.physical, power: 94, accuracy: 82, maxPp: 15, tier: 4, minLevel: 55, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Trance Grip', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 94, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Echo Pulse', type: 'psychic', category: MoveCategory.physical, power: 99, accuracy: 91, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Trance Surge', type: 'psychic', category: MoveCategory.special, power: 101, accuracy: 86, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Whisper Surge', type: 'psychic', category: MoveCategory.physical, power: 96, accuracy: 80, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Echo Veil', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 78, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Vision Grip', type: 'psychic', category: MoveCategory.status, power: 0, accuracy: 89, maxPp: 6, tier: 5, minLevel: 80, timeAffinity: 'dawn', timeBonusPct: 15),
      Move(name: 'Mind Wave', type: 'psychic', category: MoveCategory.special, power: 127, accuracy: 74, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Mind Surge', type: 'psychic', category: MoveCategory.physical, power: 122, accuracy: 72, maxPp: 9, tier: 5, minLevel: 80),
      Move(name: 'Psyche Pulse', type: 'psychic', category: MoveCategory.special, power: 0, accuracy: 86, maxPp: 6, tier: 5, minLevel: 80, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Echo Surge', type: 'psychic', category: MoveCategory.physical, power: 115, accuracy: 72, maxPp: 5, tier: 5, minLevel: 80),
    ],
    'rock': [
      Move(name: 'Cairn Fall', type: 'rock', category: MoveCategory.special, power: 36, accuracy: 97, maxPp: 27, tier: 1, minLevel: 1),
      Move(name: 'Outcrop Veil', type: 'rock', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Millstone Spike', type: 'rock', category: MoveCategory.special, power: 31, accuracy: 99, maxPp: 35, tier: 1, minLevel: 1),
      Move(name: 'Granite Burst', type: 'rock', category: MoveCategory.physical, power: 42, accuracy: 95, maxPp: 34, tier: 1, minLevel: 1),
      Move(name: 'Talus Slam', type: 'rock', category: MoveCategory.special, power: 35, accuracy: 100, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Talus Shard', type: 'rock', category: MoveCategory.physical, power: 42, accuracy: 99, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Outcrop Topple', type: 'rock', category: MoveCategory.special, power: 65, accuracy: 92, maxPp: 24, tier: 2, minLevel: 15, inflictsStatus: 'grounded', statusChancePct: 25),
      Move(name: 'Granite Slam', type: 'rock', category: MoveCategory.physical, power: 55, accuracy: 96, maxPp: 22, tier: 2, minLevel: 15, inflictsStatus: 'grounded', statusChancePct: 25),
      Move(name: 'Outcrop Slam', type: 'rock', category: MoveCategory.special, power: 56, accuracy: 90, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Outcrop Grind', type: 'rock', category: MoveCategory.physical, power: 51, accuracy: 100, maxPp: 22, tier: 2, minLevel: 15, scalesWithTargetWeight: true),
      Move(name: 'Boulder Fall', type: 'rock', category: MoveCategory.special, power: 59, accuracy: 100, maxPp: 23, tier: 2, minLevel: 15, inflictsStatus: 'grounded', statusChancePct: 25),
      Move(name: 'Millstone Shard', type: 'rock', category: MoveCategory.physical, power: 61, accuracy: 97, maxPp: 24, tier: 2, minLevel: 15),
      Move(name: 'Cairn Grind', type: 'rock', category: MoveCategory.special, power: 70, accuracy: 85, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Talus Burst', type: 'rock', category: MoveCategory.physical, power: 84, accuracy: 92, maxPp: 18, tier: 3, minLevel: 35),
      Move(name: 'Granite Fall', type: 'rock', category: MoveCategory.special, power: 84, accuracy: 90, maxPp: 18, tier: 3, minLevel: 35),
      Move(name: 'Talus Topple', type: 'rock', category: MoveCategory.physical, power: 72, accuracy: 89, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Granite Shard', type: 'rock', category: MoveCategory.special, power: 72, accuracy: 99, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Millstone Burst', type: 'rock', category: MoveCategory.physical, power: 71, accuracy: 86, maxPp: 20, tier: 3, minLevel: 35, scalesWithTargetWeight: true),
      Move(name: 'Boulder Slam', type: 'rock', category: MoveCategory.special, power: 92, accuracy: 81, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Shale Burst', type: 'rock', category: MoveCategory.physical, power: 94, accuracy: 80, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Cairn Crush', type: 'rock', category: MoveCategory.special, power: 93, accuracy: 86, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Cairn Toss', type: 'rock', category: MoveCategory.physical, power: 105, accuracy: 89, maxPp: 11, tier: 4, minLevel: 55),
      Move(name: 'Quartz Shard', type: 'rock', category: MoveCategory.special, power: 97, accuracy: 82, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Shale Spike', type: 'rock', category: MoveCategory.physical, power: 98, accuracy: 85, maxPp: 12, tier: 4, minLevel: 55),
      Move(name: 'Cairn Shard', type: 'rock', category: MoveCategory.special, power: 0, accuracy: 84, maxPp: 6, tier: 5, minLevel: 80, inflictsStatus: 'grounded', statusChancePct: 25),
      Move(name: 'Shale Slam', type: 'rock', category: MoveCategory.physical, power: 118, accuracy: 89, maxPp: 9, tier: 5, minLevel: 80, scalesWithTargetWeight: true),
      Move(name: 'Cairn Burst', type: 'rock', category: MoveCategory.special, power: 111, accuracy: 76, maxPp: 6, tier: 5, minLevel: 80),
      Move(name: 'Flint Spike', type: 'rock', category: MoveCategory.physical, power: 130, accuracy: 78, maxPp: 10, tier: 5, minLevel: 80, scalesWithTargetWeight: true),
      Move(name: 'Cobble Fall', type: 'rock', category: MoveCategory.special, power: 115, accuracy: 78, maxPp: 5, tier: 5, minLevel: 80),
      Move(name: 'Boulder Grind', type: 'rock', category: MoveCategory.physical, power: 111, accuracy: 90, maxPp: 7, tier: 5, minLevel: 80),
    ],
    'dark': [
      Move(name: 'Void Burst', type: 'dark', category: MoveCategory.special, power: 44, accuracy: 99, maxPp: 33, tier: 1, minLevel: 1),
      Move(name: 'Gloom Coil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 33, tier: 1, minLevel: 1),
      Move(name: 'Gloom Veil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Murk Coil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Abyss Spiral', type: 'dark', category: MoveCategory.special, power: 34, accuracy: 97, maxPp: 30, tier: 1, minLevel: 1),
      Move(name: 'Shadow Veil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 28, tier: 1, minLevel: 1),
      Move(name: 'Murk Shroud', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 25, tier: 2, minLevel: 15),
      Move(name: 'Umbra Snare', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 22, tier: 2, minLevel: 15, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Murk Veil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 98, maxPp: 21, tier: 2, minLevel: 15, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Umbra Creep', type: 'dark', category: MoveCategory.physical, power: 61, accuracy: 90, maxPp: 21, tier: 2, minLevel: 15),
      Move(name: 'Eclipse Veil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 95, maxPp: 20, tier: 2, minLevel: 15, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Void Creep', type: 'dark', category: MoveCategory.physical, power: 61, accuracy: 98, maxPp: 21, tier: 2, minLevel: 15),
      Move(name: 'Void Lash', type: 'dark', category: MoveCategory.special, power: 79, accuracy: 89, maxPp: 16, tier: 3, minLevel: 35),
      Move(name: 'Murk Grip', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 95, maxPp: 16, tier: 3, minLevel: 35, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Gloom Strike', type: 'dark', category: MoveCategory.special, power: 74, accuracy: 99, maxPp: 15, tier: 3, minLevel: 35, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Nightfall Snare', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 17, tier: 3, minLevel: 35),
      Move(name: 'Abyss Lash', type: 'dark', category: MoveCategory.special, power: 71, accuracy: 96, maxPp: 19, tier: 3, minLevel: 35),
      Move(name: 'Eclipse Creep', type: 'dark', category: MoveCategory.physical, power: 84, accuracy: 100, maxPp: 16, tier: 3, minLevel: 35, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Abyss Shroud', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 86, maxPp: 14, tier: 4, minLevel: 55, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Abyss Snare', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 90, maxPp: 10, tier: 4, minLevel: 55),
      Move(name: 'Twilight Lash', type: 'dark', category: MoveCategory.special, power: 93, accuracy: 80, maxPp: 14, tier: 4, minLevel: 55),
      Move(name: 'Void Coil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 89, maxPp: 13, tier: 4, minLevel: 55, inflictsStatus: 'rattled', statusChancePct: 25),
      Move(name: 'Gloom Shroud', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 94, maxPp: 10, tier: 4, minLevel: 55, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Eclipse Shroud', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 85, maxPp: 13, tier: 4, minLevel: 55),
      Move(name: 'Murk Burst', type: 'dark', category: MoveCategory.special, power: 124, accuracy: 72, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Dusk Coil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 82, maxPp: 5, tier: 5, minLevel: 80, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Gloom Burst', type: 'dark', category: MoveCategory.special, power: 113, accuracy: 80, maxPp: 10, tier: 5, minLevel: 80),
      Move(name: 'Umbra Coil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 76, maxPp: 7, tier: 5, minLevel: 80),
      Move(name: 'Nightfall Coil', type: 'dark', category: MoveCategory.status, power: 0, accuracy: 91, maxPp: 7, tier: 5, minLevel: 80, timeAffinity: 'night', timeBonusPct: 15),
      Move(name: 'Shadow Strike', type: 'dark', category: MoveCategory.physical, power: 112, accuracy: 86, maxPp: 5, tier: 5, minLevel: 80, timeAffinity: 'night', timeBonusPct: 15),
    ],
  };

  /// Moves any Wildkin can learn, regardless of type.
  static const List<Move> universal = [
    Move(name: 'Fierce Charge', type: 'universal', category: MoveCategory.physical, power: 36, accuracy: 96, maxPp: 30, tier: 1, minLevel: 1),
    Move(name: 'Rapid Slam', type: 'universal', category: MoveCategory.special, power: 36, accuracy: 98, maxPp: 30, tier: 1, minLevel: 1),
    Move(name: 'Primal Slam', type: 'universal', category: MoveCategory.physical, power: 37, accuracy: 98, maxPp: 35, tier: 1, minLevel: 1),
    Move(name: 'Fierce Counter', type: 'universal', category: MoveCategory.physical, power: 45, accuracy: 98, maxPp: 33, tier: 1, minLevel: 1),
    Move(name: 'Bold Clash', type: 'universal', category: MoveCategory.special, power: 30, accuracy: 95, maxPp: 31, tier: 1, minLevel: 1),
    Move(name: 'Rapid Charge', type: 'universal', category: MoveCategory.physical, power: 37, accuracy: 99, maxPp: 29, tier: 1, minLevel: 1),
    Move(name: 'Quick Sweep', type: 'universal', category: MoveCategory.physical, power: 36, accuracy: 98, maxPp: 34, tier: 1, minLevel: 1),
    Move(name: 'Feral Clash', type: 'universal', category: MoveCategory.special, power: 32, accuracy: 99, maxPp: 27, tier: 1, minLevel: 1),
    Move(name: 'Brave Guard', type: 'universal', category: MoveCategory.status, power: 0, accuracy: 100, maxPp: 25, tier: 1, minLevel: 1),
    Move(name: 'Rapid Pounce', type: 'universal', category: MoveCategory.physical, power: 33, accuracy: 95, maxPp: 34, tier: 1, minLevel: 1),
    Move(name: 'Fierce Bash', type: 'universal', category: MoveCategory.special, power: 55, accuracy: 95, maxPp: 21, tier: 2, minLevel: 15),
    Move(name: 'Wild Barrage', type: 'universal', category: MoveCategory.physical, power: 50, accuracy: 90, maxPp: 21, tier: 2, minLevel: 15),
    Move(name: 'Feral Assault', type: 'universal', category: MoveCategory.physical, power: 51, accuracy: 91, maxPp: 25, tier: 2, minLevel: 15),
    Move(name: 'Feral Barrage', type: 'universal', category: MoveCategory.special, power: 61, accuracy: 93, maxPp: 24, tier: 2, minLevel: 15),
    Move(name: 'Primal Clash', type: 'universal', category: MoveCategory.physical, power: 52, accuracy: 96, maxPp: 20, tier: 2, minLevel: 15),
    Move(name: 'Vigor Bash', type: 'universal', category: MoveCategory.physical, power: 56, accuracy: 91, maxPp: 20, tier: 2, minLevel: 15),
    Move(name: 'True Barrage', type: 'universal', category: MoveCategory.special, power: 52, accuracy: 100, maxPp: 25, tier: 2, minLevel: 15),
    Move(name: 'Fierce Assault', type: 'universal', category: MoveCategory.physical, power: 53, accuracy: 92, maxPp: 20, tier: 2, minLevel: 15),
    Move(name: 'Rapid Dash', type: 'universal', category: MoveCategory.physical, power: 56, accuracy: 94, maxPp: 22, tier: 2, minLevel: 15),
    Move(name: 'Wild Sweep', type: 'universal', category: MoveCategory.special, power: 58, accuracy: 90, maxPp: 22, tier: 2, minLevel: 15),
    Move(name: 'Bold Strike', type: 'universal', category: MoveCategory.physical, power: 79, accuracy: 86, maxPp: 20, tier: 3, minLevel: 35),
    Move(name: 'Hardy Barrage', type: 'universal', category: MoveCategory.physical, power: 80, accuracy: 100, maxPp: 17, tier: 3, minLevel: 35),
    Move(name: 'Quick Slam', type: 'universal', category: MoveCategory.special, power: 70, accuracy: 98, maxPp: 15, tier: 3, minLevel: 35),
    Move(name: 'Primal Assault', type: 'universal', category: MoveCategory.physical, power: 73, accuracy: 96, maxPp: 18, tier: 3, minLevel: 35),
    Move(name: 'Bold Charge', type: 'universal', category: MoveCategory.physical, power: 76, accuracy: 87, maxPp: 19, tier: 3, minLevel: 35),
    Move(name: 'Bold Rush', type: 'universal', category: MoveCategory.special, power: 75, accuracy: 98, maxPp: 15, tier: 3, minLevel: 35),
    Move(name: 'Primal Uppercut', type: 'universal', category: MoveCategory.physical, power: 79, accuracy: 86, maxPp: 15, tier: 3, minLevel: 35),
    Move(name: 'Hardy Strike', type: 'universal', category: MoveCategory.physical, power: 73, accuracy: 100, maxPp: 20, tier: 3, minLevel: 35),
    Move(name: 'Quick Uppercut', type: 'universal', category: MoveCategory.special, power: 75, accuracy: 100, maxPp: 19, tier: 3, minLevel: 35),
    Move(name: 'Grit Strike', type: 'universal', category: MoveCategory.physical, power: 78, accuracy: 90, maxPp: 17, tier: 3, minLevel: 35),
    Move(name: 'Bold Pounce', type: 'universal', category: MoveCategory.physical, power: 97, accuracy: 95, maxPp: 11, tier: 4, minLevel: 55),
    Move(name: 'Rapid Barrage', type: 'universal', category: MoveCategory.special, power: 92, accuracy: 95, maxPp: 15, tier: 4, minLevel: 55),
    Move(name: 'Brave Uppercut', type: 'universal', category: MoveCategory.physical, power: 93, accuracy: 90, maxPp: 12, tier: 4, minLevel: 55),
    Move(name: 'Feral Strike', type: 'universal', category: MoveCategory.physical, power: 102, accuracy: 82, maxPp: 13, tier: 4, minLevel: 55),
    Move(name: 'Bold Guard', type: 'universal', category: MoveCategory.status, power: 0, accuracy: 96, maxPp: 11, tier: 4, minLevel: 55),
    Move(name: 'Grit Clash', type: 'universal', category: MoveCategory.physical, power: 103, accuracy: 85, maxPp: 13, tier: 4, minLevel: 55),
    Move(name: 'Wild Assault', type: 'universal', category: MoveCategory.physical, power: 97, accuracy: 94, maxPp: 11, tier: 4, minLevel: 55),
    Move(name: 'Iron Strike', type: 'universal', category: MoveCategory.special, power: 91, accuracy: 91, maxPp: 14, tier: 4, minLevel: 55),
    Move(name: 'Rapid Sweep', type: 'universal', category: MoveCategory.physical, power: 94, accuracy: 94, maxPp: 15, tier: 4, minLevel: 55),
    Move(name: 'Feral Dash', type: 'universal', category: MoveCategory.physical, power: 100, accuracy: 85, maxPp: 13, tier: 4, minLevel: 55),
    Move(name: 'Bold Barrage', type: 'universal', category: MoveCategory.special, power: 118, accuracy: 88, maxPp: 6, tier: 5, minLevel: 80),
    Move(name: 'True Rush', type: 'universal', category: MoveCategory.physical, power: 124, accuracy: 90, maxPp: 10, tier: 5, minLevel: 80),
    Move(name: 'True Clash', type: 'universal', category: MoveCategory.physical, power: 116, accuracy: 78, maxPp: 7, tier: 5, minLevel: 80),
    Move(name: 'Rapid Clash', type: 'universal', category: MoveCategory.special, power: 129, accuracy: 74, maxPp: 10, tier: 5, minLevel: 80),
    Move(name: 'Bold Bash', type: 'universal', category: MoveCategory.physical, power: 117, accuracy: 80, maxPp: 9, tier: 5, minLevel: 80),
    Move(name: 'Feral Slam', type: 'universal', category: MoveCategory.physical, power: 115, accuracy: 77, maxPp: 7, tier: 5, minLevel: 80),
    Move(name: 'Feral Uppercut', type: 'universal', category: MoveCategory.special, power: 118, accuracy: 73, maxPp: 6, tier: 5, minLevel: 80),
    Move(name: 'Bold Sweep', type: 'universal', category: MoveCategory.physical, power: 113, accuracy: 76, maxPp: 8, tier: 5, minLevel: 80),
    Move(name: 'Quick Bash', type: 'universal', category: MoveCategory.physical, power: 114, accuracy: 79, maxPp: 10, tier: 5, minLevel: 80),
    Move(name: 'Wild Pounce', type: 'universal', category: MoveCategory.special, power: 118, accuracy: 76, maxPp: 5, tier: 5, minLevel: 80),
  ];


  List<Move> starterMoves(List<String> types, {Random? random}) {
    final rng = random ?? Random();
    final pool = <Move>[];
    for (final type in types) {
      pool.addAll(_movesOfTier(type, 1));
    }
    pool.addAll(_universalOfTier(1));
    if (types.isNotEmpty) pool.addAll(_movesOfTier(types.first, 1));

    pool.shuffle(rng);
    final unique = <String, Move>{};
    for (final move in pool) {
      unique[move.name] = move;
      if (unique.length == 4) break;
    }
    return unique.values.toList();
  }

  Move? nextMoveToLearn({
    required List<String> types,
    required int level,
    required List<String> alreadyKnownNames,
    Random? random,
  }) {
    final rng = random ?? Random();
    final targetTier = level >= 80
        ? 5
        : (level >= 55 ? 4 : (level >= 35 ? 3 : (level >= 15 ? 2 : 1)));

    final candidates = <Move>[];
    for (final type in types) {
      candidates.addAll(
        _movesOfTier(type, targetTier)
            .where((m) => !alreadyKnownNames.contains(m.name)),
      );
    }
    candidates.addAll(
      _universalOfTier(targetTier).where((m) => !alreadyKnownNames.contains(m.name)),
    );
    if (candidates.isEmpty) return null;
    candidates.shuffle(rng);
    return candidates.first;
  }

  List<Move> _movesOfTier(String type, int tier) {
    final all = _byType[type.toLowerCase()] ?? const [];
    return all.where((m) => m.tier == tier).toList();
  }

  List<Move> _universalOfTier(int tier) =>
      universal.where((m) => m.tier == tier).toList();
}
