// Port of lib/services/movepool.dart. Same table, same keys
// expected by Move.fromJson on the Flutter side (now extended with
// min_level and the weather/time/status/weight mechanics fields).
// Only starterMoves() is needed here for capture (tier 1); tiers
// 2-5 stay ready for a future evolve-wildkin function.
//
// All move names are original, matching movepool.dart.

export type MoveCategory = "physical" | "special" | "status";

export interface MoveJson {
  name: string; type: string; category: MoveCategory;
  power: number; accuracy: number; max_pp: number; tier: number; min_level: number;
  weather_affinity?: string; weather_bonus_pct?: number;
  time_affinity?: string; time_bonus_pct?: number;
  inflicts_status?: string; status_chance_pct?: number;
  scales_with_target_weight?: boolean;
}

const BY_TYPE: Record<string, MoveJson[]> = {
  fire: [
    { name: "Flare Spiral", type: "fire", category: "special", power: 40, accuracy: 96, max_pp: 31, tier: 1, min_level: 1 },
    { name: "Flare Burst", type: "fire", category: "physical", power: 31, accuracy: 95, max_pp: 33, tier: 1, min_level: 1 },
    { name: "Smolder Burst", type: "fire", category: "special", power: 33, accuracy: 97, max_pp: 34, tier: 1, min_level: 1 },
    { name: "Cinder Flurry", type: "fire", category: "physical", power: 31, accuracy: 99, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Kindling Veil", type: "fire", category: "status", power: 0, accuracy: 100, max_pp: 31, tier: 1, min_level: 1 },
    { name: "Pyre Lash", type: "fire", category: "physical", power: 43, accuracy: 95, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Cinder Burst", type: "fire", category: "special", power: 52, accuracy: 98, max_pp: 23, tier: 2, min_level: 15, weather_affinity: "fire", weather_bonus_pct: 20 },
    { name: "Ashfall Lash", type: "fire", category: "physical", power: 57, accuracy: 100, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Blaze Veil", type: "fire", category: "status", power: 0, accuracy: 100, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Ashfall Wave", type: "fire", category: "physical", power: 57, accuracy: 90, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Ashfall Surge", type: "fire", category: "special", power: 59, accuracy: 96, max_pp: 21, tier: 2, min_level: 15 },
    { name: "Blaze Lash", type: "fire", category: "physical", power: 59, accuracy: 98, max_pp: 25, tier: 2, min_level: 15, weather_affinity: "fire", weather_bonus_pct: 20 },
    { name: "Pyre Veil", type: "fire", category: "status", power: 0, accuracy: 93, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Pyre Storm", type: "fire", category: "physical", power: 71, accuracy: 91, max_pp: 18, tier: 3, min_level: 35 },
    { name: "Ashfall Spiral", type: "fire", category: "special", power: 83, accuracy: 95, max_pp: 18, tier: 3, min_level: 35 },
    { name: "Flare Veil", type: "fire", category: "status", power: 0, accuracy: 100, max_pp: 17, tier: 3, min_level: 35, weather_affinity: "fire", weather_bonus_pct: 20 },
    { name: "Flare Wave", type: "fire", category: "special", power: 77, accuracy: 87, max_pp: 19, tier: 3, min_level: 35, weather_affinity: "fire", weather_bonus_pct: 20 },
    { name: "Smolder Spiral", type: "fire", category: "physical", power: 80, accuracy: 99, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Ashfall Storm", type: "fire", category: "special", power: 92, accuracy: 83, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Magma Bloom", type: "fire", category: "physical", power: 100, accuracy: 84, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Magma Lash", type: "fire", category: "special", power: 92, accuracy: 90, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Scorch Burst", type: "fire", category: "physical", power: 105, accuracy: 94, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Magma Spiral", type: "fire", category: "special", power: 98, accuracy: 95, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Smolder Storm", type: "fire", category: "physical", power: 91, accuracy: 89, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Wildfire Lash", type: "fire", category: "special", power: 124, accuracy: 79, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Flare Flurry", type: "fire", category: "physical", power: 121, accuracy: 70, max_pp: 8, tier: 5, min_level: 80 },
    { name: "Wildfire Surge", type: "fire", category: "special", power: 129, accuracy: 73, max_pp: 8, tier: 5, min_level: 80, weather_affinity: "fire", weather_bonus_pct: 20 },
    { name: "Scorch Storm", type: "fire", category: "physical", power: 114, accuracy: 77, max_pp: 8, tier: 5, min_level: 80 },
    { name: "Wildfire Bloom", type: "fire", category: "special", power: 125, accuracy: 72, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Magma Surge", type: "fire", category: "physical", power: 127, accuracy: 78, max_pp: 6, tier: 5, min_level: 80 },
  ],
  water: [
    { name: "Deluge Drench", type: "water", category: "special", power: 38, accuracy: 100, max_pp: 31, tier: 1, min_level: 1 },
    { name: "Torrent Swell", type: "water", category: "physical", power: 41, accuracy: 100, max_pp: 31, tier: 1, min_level: 1 },
    { name: "Tide Flow", type: "water", category: "special", power: 37, accuracy: 96, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Current Veil", type: "water", category: "status", power: 0, accuracy: 100, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Cascade Crash", type: "water", category: "special", power: 37, accuracy: 95, max_pp: 32, tier: 1, min_level: 1 },
    { name: "Torrent Lash", type: "water", category: "physical", power: 35, accuracy: 97, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Torrent Spiral", type: "water", category: "special", power: 50, accuracy: 92, max_pp: 23, tier: 2, min_level: 15 },
    { name: "Undertow Churn", type: "water", category: "physical", power: 60, accuracy: 92, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Torrent Flow", type: "water", category: "special", power: 51, accuracy: 97, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Deluge Spiral", type: "water", category: "physical", power: 62, accuracy: 96, max_pp: 23, tier: 2, min_level: 15 },
    { name: "Wellspring Flow", type: "water", category: "special", power: 65, accuracy: 100, max_pp: 23, tier: 2, min_level: 15, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Cascade Drench", type: "water", category: "physical", power: 56, accuracy: 97, max_pp: 21, tier: 2, min_level: 15, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Riptide Ripple", type: "water", category: "special", power: 73, accuracy: 85, max_pp: 19, tier: 3, min_level: 35, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Brine Lash", type: "water", category: "physical", power: 81, accuracy: 85, max_pp: 15, tier: 3, min_level: 35 },
    { name: "Brine Spiral", type: "water", category: "special", power: 82, accuracy: 89, max_pp: 20, tier: 3, min_level: 35, inflicts_status: "waterlogged", status_chance_pct: 25 },
    { name: "Tide Lash", type: "water", category: "physical", power: 85, accuracy: 88, max_pp: 15, tier: 3, min_level: 35 },
    { name: "Cascade Ripple", type: "water", category: "special", power: 84, accuracy: 100, max_pp: 18, tier: 3, min_level: 35, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Riptide Drench", type: "water", category: "physical", power: 73, accuracy: 95, max_pp: 20, tier: 3, min_level: 35, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Undertow Surge", type: "water", category: "special", power: 90, accuracy: 86, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Tide Spiral", type: "water", category: "physical", power: 90, accuracy: 89, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Brine Drench", type: "water", category: "special", power: 98, accuracy: 91, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Maelstrom Lash", type: "water", category: "physical", power: 97, accuracy: 90, max_pp: 15, tier: 4, min_level: 55, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Tide Crash", type: "water", category: "special", power: 97, accuracy: 92, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Deluge Veil", type: "water", category: "status", power: 0, accuracy: 100, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Wellspring Lash", type: "water", category: "special", power: 110, accuracy: 78, max_pp: 8, tier: 5, min_level: 80, inflicts_status: "waterlogged", status_chance_pct: 25 },
    { name: "Maelstrom Swell", type: "water", category: "physical", power: 121, accuracy: 81, max_pp: 5, tier: 5, min_level: 80, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Tide Veil", type: "water", category: "status", power: 0, accuracy: 81, max_pp: 7, tier: 5, min_level: 80, weather_affinity: "water", weather_bonus_pct: 20 },
    { name: "Wellspring Swell", type: "water", category: "physical", power: 125, accuracy: 90, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Current Flow", type: "water", category: "special", power: 112, accuracy: 73, max_pp: 8, tier: 5, min_level: 80 },
    { name: "Undertow Swell", type: "water", category: "physical", power: 116, accuracy: 85, max_pp: 6, tier: 5, min_level: 80 },
  ],
  electric: [
    { name: "Arc Flicker", type: "electric", category: "special", power: 40, accuracy: 95, max_pp: 31, tier: 1, min_level: 1 },
    { name: "Coil Blitz", type: "electric", category: "physical", power: 44, accuracy: 98, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Arc Blitz", type: "electric", category: "special", power: 35, accuracy: 96, max_pp: 27, tier: 1, min_level: 1 },
    { name: "Volt Flicker", type: "electric", category: "physical", power: 30, accuracy: 96, max_pp: 34, tier: 1, min_level: 1 },
    { name: "Arc Surge", type: "electric", category: "special", power: 44, accuracy: 100, max_pp: 27, tier: 1, min_level: 1 },
    { name: "Jolt Flicker", type: "electric", category: "physical", power: 45, accuracy: 100, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Amp Flicker", type: "electric", category: "special", power: 54, accuracy: 98, max_pp: 24, tier: 2, min_level: 15, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Volt Strike", type: "electric", category: "physical", power: 53, accuracy: 98, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Jolt Storm", type: "electric", category: "special", power: 63, accuracy: 93, max_pp: 21, tier: 2, min_level: 15, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Jolt Blitz", type: "electric", category: "physical", power: 59, accuracy: 98, max_pp: 21, tier: 2, min_level: 15 },
    { name: "Circuit Lash", type: "electric", category: "special", power: 60, accuracy: 94, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Jolt Lash", type: "electric", category: "physical", power: 54, accuracy: 90, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Volt Pulse", type: "electric", category: "special", power: 84, accuracy: 98, max_pp: 19, tier: 3, min_level: 35, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Jolt Surge", type: "electric", category: "physical", power: 70, accuracy: 99, max_pp: 16, tier: 3, min_level: 35 },
    { name: "Volt Surge", type: "electric", category: "special", power: 74, accuracy: 90, max_pp: 16, tier: 3, min_level: 35 },
    { name: "Flux Blitz", type: "electric", category: "physical", power: 73, accuracy: 86, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Amp Blitz", type: "electric", category: "special", power: 85, accuracy: 88, max_pp: 19, tier: 3, min_level: 35, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Coil Lash", type: "electric", category: "physical", power: 78, accuracy: 86, max_pp: 15, tier: 3, min_level: 35 },
    { name: "Flux Surge", type: "electric", category: "special", power: 90, accuracy: 82, max_pp: 13, tier: 4, min_level: 55, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Coil Pulse", type: "electric", category: "physical", power: 98, accuracy: 94, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Charge Burst", type: "electric", category: "special", power: 105, accuracy: 87, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Volt Lash", type: "electric", category: "physical", power: 98, accuracy: 86, max_pp: 13, tier: 4, min_level: 55, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Static Crackle", type: "electric", category: "special", power: 102, accuracy: 94, max_pp: 12, tier: 4, min_level: 55, weather_affinity: "electric", weather_bonus_pct: 20 },
    { name: "Amp Storm", type: "electric", category: "physical", power: 103, accuracy: 82, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Coil Discharge", type: "electric", category: "special", power: 113, accuracy: 74, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Fuse Burst", type: "electric", category: "physical", power: 121, accuracy: 74, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Amp Crackle", type: "electric", category: "special", power: 124, accuracy: 77, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Charge Surge", type: "electric", category: "physical", power: 122, accuracy: 85, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Jolt Discharge", type: "electric", category: "special", power: 117, accuracy: 75, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Circuit Strike", type: "electric", category: "physical", power: 126, accuracy: 82, max_pp: 7, tier: 5, min_level: 80 },
  ],
  grass: [
    { name: "Vine Burst", type: "grass", category: "special", power: 41, accuracy: 97, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Bloom Sprawl", type: "grass", category: "physical", power: 41, accuracy: 95, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Sap Drain", type: "grass", category: "special", power: 44, accuracy: 98, max_pp: 25, tier: 1, min_level: 1 },
    { name: "Bark Drain", type: "grass", category: "physical", power: 42, accuracy: 97, max_pp: 33, tier: 1, min_level: 1 },
    { name: "Thorn Lash", type: "grass", category: "special", power: 39, accuracy: 99, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Bramble Coil", type: "grass", category: "status", power: 0, accuracy: 100, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Fern Snap", type: "grass", category: "special", power: 52, accuracy: 94, max_pp: 22, tier: 2, min_level: 15, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Thorn Coil", type: "grass", category: "status", power: 0, accuracy: 97, max_pp: 23, tier: 2, min_level: 15 },
    { name: "Sap Veil", type: "grass", category: "status", power: 0, accuracy: 100, max_pp: 21, tier: 2, min_level: 15 },
    { name: "Moss Burst", type: "grass", category: "physical", power: 65, accuracy: 95, max_pp: 20, tier: 2, min_level: 15, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Fern Bind", type: "grass", category: "status", power: 0, accuracy: 96, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Bramble Lash", type: "grass", category: "physical", power: 52, accuracy: 94, max_pp: 20, tier: 2, min_level: 15 },
    { name: "Vine Bind", type: "grass", category: "status", power: 0, accuracy: 92, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Pollen Sprawl", type: "grass", category: "physical", power: 84, accuracy: 85, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Thorn Bind", type: "grass", category: "status", power: 0, accuracy: 98, max_pp: 19, tier: 3, min_level: 35, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Moss Coil", type: "grass", category: "status", power: 0, accuracy: 95, max_pp: 17, tier: 3, min_level: 35, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Moss Bind", type: "grass", category: "status", power: 0, accuracy: 99, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Bark Sprawl", type: "grass", category: "physical", power: 79, accuracy: 99, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Sap Bind", type: "grass", category: "status", power: 0, accuracy: 96, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Sap Lash", type: "grass", category: "physical", power: 91, accuracy: 80, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Moss Lash", type: "grass", category: "special", power: 96, accuracy: 95, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Root Drain", type: "grass", category: "physical", power: 93, accuracy: 93, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Vine Veil", type: "grass", category: "status", power: 0, accuracy: 94, max_pp: 15, tier: 4, min_level: 55, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Bramble Sprawl", type: "grass", category: "physical", power: 100, accuracy: 86, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Moss Sprawl", type: "grass", category: "special", power: 114, accuracy: 82, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Moss Veil", type: "grass", category: "status", power: 0, accuracy: 75, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Thorn Drain", type: "grass", category: "special", power: 118, accuracy: 83, max_pp: 6, tier: 5, min_level: 80, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Moss Spiral", type: "grass", category: "physical", power: 126, accuracy: 79, max_pp: 9, tier: 5, min_level: 80, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Fern Coil", type: "grass", category: "status", power: 0, accuracy: 89, max_pp: 6, tier: 5, min_level: 80, weather_affinity: "grass", weather_bonus_pct: 20 },
    { name: "Bloom Weave", type: "grass", category: "physical", power: 110, accuracy: 78, max_pp: 7, tier: 5, min_level: 80 },
  ],
  ice: [
    { name: "Crystal Spiral", type: "ice", category: "special", power: 40, accuracy: 96, max_pp: 25, tier: 1, min_level: 1 },
    { name: "Rime Burst", type: "ice", category: "physical", power: 39, accuracy: 96, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Crystal Squall", type: "ice", category: "special", power: 35, accuracy: 95, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Hoarfrost Storm", type: "ice", category: "physical", power: 42, accuracy: 95, max_pp: 32, tier: 1, min_level: 1 },
    { name: "Sleet Drift", type: "ice", category: "special", power: 38, accuracy: 99, max_pp: 35, tier: 1, min_level: 1 },
    { name: "Frost Squall", type: "ice", category: "physical", power: 36, accuracy: 96, max_pp: 33, tier: 1, min_level: 1 },
    { name: "Glaze Squall", type: "ice", category: "special", power: 50, accuracy: 91, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Permafrost Shard", type: "ice", category: "physical", power: 54, accuracy: 96, max_pp: 24, tier: 2, min_level: 15, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Hoarfrost Burst", type: "ice", category: "special", power: 59, accuracy: 94, max_pp: 25, tier: 2, min_level: 15, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Icicle Spike", type: "ice", category: "physical", power: 62, accuracy: 95, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Tundra Shard", type: "ice", category: "special", power: 54, accuracy: 94, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Hoarfrost Spiral", type: "ice", category: "physical", power: 54, accuracy: 90, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Sleet Squall", type: "ice", category: "special", power: 83, accuracy: 89, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Glaze Burst", type: "ice", category: "physical", power: 70, accuracy: 92, max_pp: 15, tier: 3, min_level: 35, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Icicle Burst", type: "ice", category: "special", power: 81, accuracy: 88, max_pp: 18, tier: 3, min_level: 35 },
    { name: "Hoarfrost Lash", type: "ice", category: "physical", power: 71, accuracy: 85, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Tundra Burst", type: "ice", category: "special", power: 77, accuracy: 100, max_pp: 17, tier: 3, min_level: 35, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Glaze Drift", type: "ice", category: "physical", power: 72, accuracy: 87, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Icicle Shard", type: "ice", category: "special", power: 98, accuracy: 82, max_pp: 12, tier: 4, min_level: 55, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Glacial Spike", type: "ice", category: "physical", power: 97, accuracy: 94, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Crystal Storm", type: "ice", category: "special", power: 92, accuracy: 95, max_pp: 15, tier: 4, min_level: 55, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Sleet Burst", type: "ice", category: "physical", power: 96, accuracy: 82, max_pp: 14, tier: 4, min_level: 55, inflicts_status: "chilled", status_chance_pct: 25 },
    { name: "Rime Drift", type: "ice", category: "special", power: 99, accuracy: 84, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Permafrost Spike", type: "ice", category: "physical", power: 105, accuracy: 88, max_pp: 15, tier: 4, min_level: 55, weather_affinity: "ice", weather_bonus_pct: 20 },
    { name: "Rime Squall", type: "ice", category: "special", power: 125, accuracy: 79, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Tundra Storm", type: "ice", category: "physical", power: 124, accuracy: 84, max_pp: 8, tier: 5, min_level: 80 },
    { name: "Crystal Crackle", type: "ice", category: "special", power: 127, accuracy: 76, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Frost Drift", type: "ice", category: "physical", power: 125, accuracy: 70, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Icicle Spiral", type: "ice", category: "special", power: 126, accuracy: 84, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Frost Shard", type: "ice", category: "physical", power: 116, accuracy: 72, max_pp: 9, tier: 5, min_level: 80, inflicts_status: "chilled", status_chance_pct: 25 },
  ],
  poison: [
    { name: "Corrosion Fester", type: "poison", category: "special", power: 34, accuracy: 99, max_pp: 35, tier: 1, min_level: 1 },
    { name: "Rot Burst", type: "poison", category: "physical", power: 38, accuracy: 95, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Corrosion Lash", type: "poison", category: "special", power: 37, accuracy: 98, max_pp: 32, tier: 1, min_level: 1 },
    { name: "Bile Prick", type: "poison", category: "physical", power: 42, accuracy: 95, max_pp: 27, tier: 1, min_level: 1 },
    { name: "Ooze Burst", type: "poison", category: "special", power: 30, accuracy: 98, max_pp: 35, tier: 1, min_level: 1 },
    { name: "Rot Prick", type: "poison", category: "physical", power: 44, accuracy: 98, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Fume Prick", type: "poison", category: "special", power: 54, accuracy: 96, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Fume Burst", type: "poison", category: "physical", power: 53, accuracy: 95, max_pp: 20, tier: 2, min_level: 15, inflicts_status: "toxic_film", status_chance_pct: 25 },
    { name: "Miasma Lash", type: "poison", category: "special", power: 0, accuracy: 93, max_pp: 25, tier: 2, min_level: 15, inflicts_status: "toxic_film", status_chance_pct: 25 },
    { name: "Ooze Drip", type: "poison", category: "physical", power: 52, accuracy: 96, max_pp: 23, tier: 2, min_level: 15 },
    { name: "Toxin Soak", type: "poison", category: "special", power: 52, accuracy: 95, max_pp: 23, tier: 2, min_level: 15 },
    { name: "Venom Burst", type: "poison", category: "physical", power: 51, accuracy: 94, max_pp: 20, tier: 2, min_level: 15, inflicts_status: "toxic_film", status_chance_pct: 25 },
    { name: "Miasma Veil", type: "poison", category: "status", power: 0, accuracy: 97, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Blight Drip", type: "poison", category: "physical", power: 80, accuracy: 91, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Fume Spray", type: "poison", category: "special", power: 83, accuracy: 85, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Rot Veil", type: "poison", category: "status", power: 0, accuracy: 92, max_pp: 15, tier: 3, min_level: 35 },
    { name: "Rot Cloud", type: "poison", category: "special", power: 83, accuracy: 99, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Rot Fester", type: "poison", category: "physical", power: 79, accuracy: 100, max_pp: 15, tier: 3, min_level: 35 },
    { name: "Blight Veil", type: "poison", category: "status", power: 0, accuracy: 90, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Toxin Veil", type: "poison", category: "status", power: 0, accuracy: 94, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Blight Soak", type: "poison", category: "special", power: 98, accuracy: 92, max_pp: 15, tier: 4, min_level: 55, inflicts_status: "toxic_film", status_chance_pct: 25 },
    { name: "Venom Prick", type: "poison", category: "physical", power: 102, accuracy: 83, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Corrosion Prick", type: "poison", category: "special", power: 92, accuracy: 86, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Bile Drip", type: "poison", category: "physical", power: 105, accuracy: 87, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Ooze Fester", type: "poison", category: "special", power: 124, accuracy: 83, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Ooze Cloud", type: "poison", category: "physical", power: 117, accuracy: 72, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Miasma Spray", type: "poison", category: "special", power: 112, accuracy: 80, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Rot Soak", type: "poison", category: "physical", power: 128, accuracy: 76, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Toxin Prick", type: "poison", category: "special", power: 123, accuracy: 82, max_pp: 8, tier: 5, min_level: 80 },
    { name: "Venom Veil", type: "poison", category: "status", power: 0, accuracy: 87, max_pp: 7, tier: 5, min_level: 80 },
  ],
  ground: [
    { name: "Silt Strike", type: "ground", category: "special", power: 31, accuracy: 98, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Canyon Veil", type: "ground", category: "status", power: 0, accuracy: 100, max_pp: 35, tier: 1, min_level: 1 },
    { name: "Dust Shake", type: "ground", category: "special", power: 36, accuracy: 95, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Bedrock Grind", type: "ground", category: "physical", power: 37, accuracy: 98, max_pp: 31, tier: 1, min_level: 1 },
    { name: "Pitfall Slam", type: "ground", category: "special", power: 44, accuracy: 98, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Canyon Strike", type: "ground", category: "physical", power: 30, accuracy: 96, max_pp: 25, tier: 1, min_level: 1 },
    { name: "Canyon Spiral", type: "ground", category: "special", power: 63, accuracy: 97, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Sand Wave", type: "ground", category: "physical", power: 52, accuracy: 96, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Crag Toss", type: "ground", category: "special", power: 64, accuracy: 93, max_pp: 20, tier: 2, min_level: 15, weather_affinity: "ground", weather_bonus_pct: 20 },
    { name: "Dust Strike", type: "ground", category: "physical", power: 53, accuracy: 100, max_pp: 23, tier: 2, min_level: 15, weather_affinity: "ground", weather_bonus_pct: 20 },
    { name: "Dust Crush", type: "ground", category: "special", power: 50, accuracy: 92, max_pp: 21, tier: 2, min_level: 15 },
    { name: "Pitfall Wave", type: "ground", category: "physical", power: 51, accuracy: 100, max_pp: 25, tier: 2, min_level: 15, weather_affinity: "ground", weather_bonus_pct: 20 },
    { name: "Tremor Toss", type: "ground", category: "special", power: 78, accuracy: 98, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Crag Crush", type: "ground", category: "physical", power: 73, accuracy: 87, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Dust Spiral", type: "ground", category: "special", power: 76, accuracy: 97, max_pp: 17, tier: 3, min_level: 35, weather_affinity: "ground", weather_bonus_pct: 20 },
    { name: "Silt Spiral", type: "ground", category: "physical", power: 70, accuracy: 94, max_pp: 18, tier: 3, min_level: 35, inflicts_status: "grounded", status_chance_pct: 25 },
    { name: "Dust Wave", type: "ground", category: "special", power: 77, accuracy: 100, max_pp: 19, tier: 3, min_level: 35, weather_affinity: "ground", weather_bonus_pct: 20 },
    { name: "Canyon Toss", type: "ground", category: "physical", power: 70, accuracy: 98, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Tremor Slam", type: "ground", category: "special", power: 91, accuracy: 80, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Rubble Toss", type: "ground", category: "physical", power: 103, accuracy: 82, max_pp: 12, tier: 4, min_level: 55, inflicts_status: "grounded", status_chance_pct: 25 },
    { name: "Rubble Wave", type: "ground", category: "special", power: 97, accuracy: 95, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Rubble Shake", type: "ground", category: "physical", power: 103, accuracy: 91, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Sand Spiral", type: "ground", category: "special", power: 90, accuracy: 89, max_pp: 15, tier: 4, min_level: 55 },
    { name: "Clay Grind", type: "ground", category: "physical", power: 92, accuracy: 86, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Dust Burst", type: "ground", category: "special", power: 119, accuracy: 76, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Clay Veil", type: "ground", category: "status", power: 0, accuracy: 84, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Clay Wave", type: "ground", category: "special", power: 125, accuracy: 89, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Clay Burst", type: "ground", category: "physical", power: 125, accuracy: 83, max_pp: 10, tier: 5, min_level: 80, scales_with_target_weight: true },
    { name: "Tremor Crush", type: "ground", category: "special", power: 114, accuracy: 82, max_pp: 5, tier: 5, min_level: 80, weather_affinity: "ground", weather_bonus_pct: 20 },
    { name: "Silt Slam", type: "ground", category: "physical", power: 123, accuracy: 71, max_pp: 10, tier: 5, min_level: 80, inflicts_status: "grounded", status_chance_pct: 25 },
  ],
  flying: [
    { name: "Zephyr Veil", type: "flying", category: "status", power: 0, accuracy: 100, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Skybound Swoop", type: "flying", category: "physical", power: 32, accuracy: 96, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Draft Swoop", type: "flying", category: "special", power: 36, accuracy: 96, max_pp: 35, tier: 1, min_level: 1 },
    { name: "Windrow Swoop", type: "flying", category: "physical", power: 44, accuracy: 95, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Zephyr Dive", type: "flying", category: "special", power: 42, accuracy: 97, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Gale Strike", type: "flying", category: "physical", power: 44, accuracy: 96, max_pp: 26, tier: 1, min_level: 1 },
    { name: "Squall Glide", type: "flying", category: "special", power: 50, accuracy: 91, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Thermal Glide", type: "flying", category: "physical", power: 63, accuracy: 91, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Thermal Strike", type: "flying", category: "special", power: 56, accuracy: 96, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Tempest Strike", type: "flying", category: "physical", power: 59, accuracy: 96, max_pp: 20, tier: 2, min_level: 15 },
    { name: "Tempest Glide", type: "flying", category: "special", power: 65, accuracy: 93, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Thermal Lash", type: "flying", category: "physical", power: 64, accuracy: 93, max_pp: 22, tier: 2, min_level: 15 },
    { name: "Thermal Burst", type: "flying", category: "special", power: 85, accuracy: 85, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Windrow Burst", type: "flying", category: "physical", power: 82, accuracy: 86, max_pp: 18, tier: 3, min_level: 35 },
    { name: "Squall Dive", type: "flying", category: "special", power: 72, accuracy: 86, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Gale Swoop", type: "flying", category: "physical", power: 72, accuracy: 95, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Windrow Dive", type: "flying", category: "special", power: 71, accuracy: 93, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Skybound Lash", type: "flying", category: "physical", power: 80, accuracy: 93, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Zephyr Whirl", type: "flying", category: "special", power: 92, accuracy: 80, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Cyclone Spiral", type: "flying", category: "physical", power: 104, accuracy: 92, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Cyclone Burst", type: "flying", category: "special", power: 105, accuracy: 84, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Windrow Storm", type: "flying", category: "physical", power: 99, accuracy: 84, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Cyclone Glide", type: "flying", category: "special", power: 100, accuracy: 94, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Skybound Glide", type: "flying", category: "physical", power: 92, accuracy: 86, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Skybound Strike", type: "flying", category: "special", power: 117, accuracy: 83, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Tempest Veil", type: "flying", category: "status", power: 0, accuracy: 92, max_pp: 9, tier: 5, min_level: 80 },
    { name: "Gale Glide", type: "flying", category: "special", power: 123, accuracy: 73, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Windrow Spiral", type: "flying", category: "physical", power: 112, accuracy: 76, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Tempest Spiral", type: "flying", category: "special", power: 124, accuracy: 75, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Gale Storm", type: "flying", category: "physical", power: 124, accuracy: 89, max_pp: 10, tier: 5, min_level: 80 },
  ],
  psychic: [
    { name: "Whisper Grip", type: "psychic", category: "status", power: 0, accuracy: 100, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Insight Grip", type: "psychic", category: "status", power: 0, accuracy: 100, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Whisper Veil", type: "psychic", category: "status", power: 0, accuracy: 100, max_pp: 29, tier: 1, min_level: 1 },
    { name: "Trance Wave", type: "psychic", category: "physical", power: 36, accuracy: 98, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Mirage Bend", type: "psychic", category: "special", power: 35, accuracy: 96, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Mind Bend", type: "psychic", category: "physical", power: 34, accuracy: 97, max_pp: 34, tier: 1, min_level: 1 },
    { name: "Trance Fracture", type: "psychic", category: "special", power: 56, accuracy: 95, max_pp: 20, tier: 2, min_level: 15 },
    { name: "Aura Veil", type: "psychic", category: "status", power: 0, accuracy: 100, max_pp: 24, tier: 2, min_level: 15, time_affinity: "dawn", time_bonus_pct: 15 },
    { name: "Mirage Surge", type: "psychic", category: "special", power: 64, accuracy: 90, max_pp: 20, tier: 2, min_level: 15, time_affinity: "dawn", time_bonus_pct: 15 },
    { name: "Reverie Pulse", type: "psychic", category: "physical", power: 64, accuracy: 95, max_pp: 20, tier: 2, min_level: 15 },
    { name: "Insight Pulse", type: "psychic", category: "special", power: 57, accuracy: 91, max_pp: 20, tier: 2, min_level: 15, time_affinity: "dawn", time_bonus_pct: 15 },
    { name: "Aura Wave", type: "psychic", category: "physical", power: 52, accuracy: 95, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Mirage Pulse", type: "psychic", category: "special", power: 84, accuracy: 93, max_pp: 20, tier: 3, min_level: 35 },
    { name: "Mind Ripple", type: "psychic", category: "physical", power: 0, accuracy: 96, max_pp: 16, tier: 3, min_level: 35, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Mirage Wave", type: "psychic", category: "special", power: 76, accuracy: 93, max_pp: 15, tier: 3, min_level: 35 },
    { name: "Psyche Grip", type: "psychic", category: "status", power: 0, accuracy: 90, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Mind Spiral", type: "psychic", category: "special", power: 81, accuracy: 90, max_pp: 19, tier: 3, min_level: 35, time_affinity: "dawn", time_bonus_pct: 15 },
    { name: "Mirage Grip", type: "psychic", category: "status", power: 0, accuracy: 100, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Trance Ripple", type: "psychic", category: "special", power: 103, accuracy: 83, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Mirage Burst", type: "psychic", category: "physical", power: 94, accuracy: 82, max_pp: 15, tier: 4, min_level: 55, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Trance Grip", type: "psychic", category: "status", power: 0, accuracy: 94, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Echo Pulse", type: "psychic", category: "physical", power: 99, accuracy: 91, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Trance Surge", type: "psychic", category: "special", power: 101, accuracy: 86, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Whisper Surge", type: "psychic", category: "physical", power: 96, accuracy: 80, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Echo Veil", type: "psychic", category: "status", power: 0, accuracy: 78, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Vision Grip", type: "psychic", category: "status", power: 0, accuracy: 89, max_pp: 6, tier: 5, min_level: 80, time_affinity: "dawn", time_bonus_pct: 15 },
    { name: "Mind Wave", type: "psychic", category: "special", power: 127, accuracy: 74, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Mind Surge", type: "psychic", category: "physical", power: 122, accuracy: 72, max_pp: 9, tier: 5, min_level: 80 },
    { name: "Psyche Pulse", type: "psychic", category: "special", power: 0, accuracy: 86, max_pp: 6, tier: 5, min_level: 80, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Echo Surge", type: "psychic", category: "physical", power: 115, accuracy: 72, max_pp: 5, tier: 5, min_level: 80 },
  ],
  rock: [
    { name: "Cairn Fall", type: "rock", category: "special", power: 36, accuracy: 97, max_pp: 27, tier: 1, min_level: 1 },
    { name: "Outcrop Veil", type: "rock", category: "status", power: 0, accuracy: 100, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Millstone Spike", type: "rock", category: "special", power: 31, accuracy: 99, max_pp: 35, tier: 1, min_level: 1 },
    { name: "Granite Burst", type: "rock", category: "physical", power: 42, accuracy: 95, max_pp: 34, tier: 1, min_level: 1 },
    { name: "Talus Slam", type: "rock", category: "special", power: 35, accuracy: 100, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Talus Shard", type: "rock", category: "physical", power: 42, accuracy: 99, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Outcrop Topple", type: "rock", category: "special", power: 65, accuracy: 92, max_pp: 24, tier: 2, min_level: 15, inflicts_status: "grounded", status_chance_pct: 25 },
    { name: "Granite Slam", type: "rock", category: "physical", power: 55, accuracy: 96, max_pp: 22, tier: 2, min_level: 15, inflicts_status: "grounded", status_chance_pct: 25 },
    { name: "Outcrop Slam", type: "rock", category: "special", power: 56, accuracy: 90, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Outcrop Grind", type: "rock", category: "physical", power: 51, accuracy: 100, max_pp: 22, tier: 2, min_level: 15, scales_with_target_weight: true },
    { name: "Boulder Fall", type: "rock", category: "special", power: 59, accuracy: 100, max_pp: 23, tier: 2, min_level: 15, inflicts_status: "grounded", status_chance_pct: 25 },
    { name: "Millstone Shard", type: "rock", category: "physical", power: 61, accuracy: 97, max_pp: 24, tier: 2, min_level: 15 },
    { name: "Cairn Grind", type: "rock", category: "special", power: 70, accuracy: 85, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Talus Burst", type: "rock", category: "physical", power: 84, accuracy: 92, max_pp: 18, tier: 3, min_level: 35 },
    { name: "Granite Fall", type: "rock", category: "special", power: 84, accuracy: 90, max_pp: 18, tier: 3, min_level: 35 },
    { name: "Talus Topple", type: "rock", category: "physical", power: 72, accuracy: 89, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Granite Shard", type: "rock", category: "special", power: 72, accuracy: 99, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Millstone Burst", type: "rock", category: "physical", power: 71, accuracy: 86, max_pp: 20, tier: 3, min_level: 35, scales_with_target_weight: true },
    { name: "Boulder Slam", type: "rock", category: "special", power: 92, accuracy: 81, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Shale Burst", type: "rock", category: "physical", power: 94, accuracy: 80, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Cairn Crush", type: "rock", category: "special", power: 93, accuracy: 86, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Cairn Toss", type: "rock", category: "physical", power: 105, accuracy: 89, max_pp: 11, tier: 4, min_level: 55 },
    { name: "Quartz Shard", type: "rock", category: "special", power: 97, accuracy: 82, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Shale Spike", type: "rock", category: "physical", power: 98, accuracy: 85, max_pp: 12, tier: 4, min_level: 55 },
    { name: "Cairn Shard", type: "rock", category: "special", power: 0, accuracy: 84, max_pp: 6, tier: 5, min_level: 80, inflicts_status: "grounded", status_chance_pct: 25 },
    { name: "Shale Slam", type: "rock", category: "physical", power: 118, accuracy: 89, max_pp: 9, tier: 5, min_level: 80, scales_with_target_weight: true },
    { name: "Cairn Burst", type: "rock", category: "special", power: 111, accuracy: 76, max_pp: 6, tier: 5, min_level: 80 },
    { name: "Flint Spike", type: "rock", category: "physical", power: 130, accuracy: 78, max_pp: 10, tier: 5, min_level: 80, scales_with_target_weight: true },
    { name: "Cobble Fall", type: "rock", category: "special", power: 115, accuracy: 78, max_pp: 5, tier: 5, min_level: 80 },
    { name: "Boulder Grind", type: "rock", category: "physical", power: 111, accuracy: 90, max_pp: 7, tier: 5, min_level: 80 },
  ],
  dark: [
    { name: "Void Burst", type: "dark", category: "special", power: 44, accuracy: 99, max_pp: 33, tier: 1, min_level: 1 },
    { name: "Gloom Coil", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 33, tier: 1, min_level: 1 },
    { name: "Gloom Veil", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Murk Coil", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Abyss Spiral", type: "dark", category: "special", power: 34, accuracy: 97, max_pp: 30, tier: 1, min_level: 1 },
    { name: "Shadow Veil", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 28, tier: 1, min_level: 1 },
    { name: "Murk Shroud", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 25, tier: 2, min_level: 15 },
    { name: "Umbra Snare", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 22, tier: 2, min_level: 15, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Murk Veil", type: "dark", category: "status", power: 0, accuracy: 98, max_pp: 21, tier: 2, min_level: 15, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Umbra Creep", type: "dark", category: "physical", power: 61, accuracy: 90, max_pp: 21, tier: 2, min_level: 15 },
    { name: "Eclipse Veil", type: "dark", category: "status", power: 0, accuracy: 95, max_pp: 20, tier: 2, min_level: 15, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Void Creep", type: "dark", category: "physical", power: 61, accuracy: 98, max_pp: 21, tier: 2, min_level: 15 },
    { name: "Void Lash", type: "dark", category: "special", power: 79, accuracy: 89, max_pp: 16, tier: 3, min_level: 35 },
    { name: "Murk Grip", type: "dark", category: "status", power: 0, accuracy: 95, max_pp: 16, tier: 3, min_level: 35, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Gloom Strike", type: "dark", category: "special", power: 74, accuracy: 99, max_pp: 15, tier: 3, min_level: 35, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Nightfall Snare", type: "dark", category: "status", power: 0, accuracy: 100, max_pp: 17, tier: 3, min_level: 35 },
    { name: "Abyss Lash", type: "dark", category: "special", power: 71, accuracy: 96, max_pp: 19, tier: 3, min_level: 35 },
    { name: "Eclipse Creep", type: "dark", category: "physical", power: 84, accuracy: 100, max_pp: 16, tier: 3, min_level: 35, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Abyss Shroud", type: "dark", category: "status", power: 0, accuracy: 86, max_pp: 14, tier: 4, min_level: 55, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Abyss Snare", type: "dark", category: "status", power: 0, accuracy: 90, max_pp: 10, tier: 4, min_level: 55 },
    { name: "Twilight Lash", type: "dark", category: "special", power: 93, accuracy: 80, max_pp: 14, tier: 4, min_level: 55 },
    { name: "Void Coil", type: "dark", category: "status", power: 0, accuracy: 89, max_pp: 13, tier: 4, min_level: 55, inflicts_status: "rattled", status_chance_pct: 25 },
    { name: "Gloom Shroud", type: "dark", category: "status", power: 0, accuracy: 94, max_pp: 10, tier: 4, min_level: 55, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Eclipse Shroud", type: "dark", category: "status", power: 0, accuracy: 85, max_pp: 13, tier: 4, min_level: 55 },
    { name: "Murk Burst", type: "dark", category: "special", power: 124, accuracy: 72, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Dusk Coil", type: "dark", category: "status", power: 0, accuracy: 82, max_pp: 5, tier: 5, min_level: 80, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Gloom Burst", type: "dark", category: "special", power: 113, accuracy: 80, max_pp: 10, tier: 5, min_level: 80 },
    { name: "Umbra Coil", type: "dark", category: "status", power: 0, accuracy: 76, max_pp: 7, tier: 5, min_level: 80 },
    { name: "Nightfall Coil", type: "dark", category: "status", power: 0, accuracy: 91, max_pp: 7, tier: 5, min_level: 80, time_affinity: "night", time_bonus_pct: 15 },
    { name: "Shadow Strike", type: "dark", category: "physical", power: 112, accuracy: 86, max_pp: 5, tier: 5, min_level: 80, time_affinity: "night", time_bonus_pct: 15 },
  ],
};

const UNIVERSAL_MOVES: MoveJson[] = [
  { name: "Fierce Charge", type: "universal", category: "physical", power: 36, accuracy: 96, max_pp: 30, tier: 1, min_level: 1 },
  { name: "Rapid Slam", type: "universal", category: "special", power: 36, accuracy: 98, max_pp: 30, tier: 1, min_level: 1 },
  { name: "Primal Slam", type: "universal", category: "physical", power: 37, accuracy: 98, max_pp: 35, tier: 1, min_level: 1 },
  { name: "Fierce Counter", type: "universal", category: "physical", power: 45, accuracy: 98, max_pp: 33, tier: 1, min_level: 1 },
  { name: "Bold Clash", type: "universal", category: "special", power: 30, accuracy: 95, max_pp: 31, tier: 1, min_level: 1 },
  { name: "Rapid Charge", type: "universal", category: "physical", power: 37, accuracy: 99, max_pp: 29, tier: 1, min_level: 1 },
  { name: "Quick Sweep", type: "universal", category: "physical", power: 36, accuracy: 98, max_pp: 34, tier: 1, min_level: 1 },
  { name: "Feral Clash", type: "universal", category: "special", power: 32, accuracy: 99, max_pp: 27, tier: 1, min_level: 1 },
  { name: "Brave Guard", type: "universal", category: "status", power: 0, accuracy: 100, max_pp: 25, tier: 1, min_level: 1 },
  { name: "Rapid Pounce", type: "universal", category: "physical", power: 33, accuracy: 95, max_pp: 34, tier: 1, min_level: 1 },
  { name: "Fierce Bash", type: "universal", category: "special", power: 55, accuracy: 95, max_pp: 21, tier: 2, min_level: 15 },
  { name: "Wild Barrage", type: "universal", category: "physical", power: 50, accuracy: 90, max_pp: 21, tier: 2, min_level: 15 },
  { name: "Feral Assault", type: "universal", category: "physical", power: 51, accuracy: 91, max_pp: 25, tier: 2, min_level: 15 },
  { name: "Feral Barrage", type: "universal", category: "special", power: 61, accuracy: 93, max_pp: 24, tier: 2, min_level: 15 },
  { name: "Primal Clash", type: "universal", category: "physical", power: 52, accuracy: 96, max_pp: 20, tier: 2, min_level: 15 },
  { name: "Vigor Bash", type: "universal", category: "physical", power: 56, accuracy: 91, max_pp: 20, tier: 2, min_level: 15 },
  { name: "True Barrage", type: "universal", category: "special", power: 52, accuracy: 100, max_pp: 25, tier: 2, min_level: 15 },
  { name: "Fierce Assault", type: "universal", category: "physical", power: 53, accuracy: 92, max_pp: 20, tier: 2, min_level: 15 },
  { name: "Rapid Dash", type: "universal", category: "physical", power: 56, accuracy: 94, max_pp: 22, tier: 2, min_level: 15 },
  { name: "Wild Sweep", type: "universal", category: "special", power: 58, accuracy: 90, max_pp: 22, tier: 2, min_level: 15 },
  { name: "Bold Strike", type: "universal", category: "physical", power: 79, accuracy: 86, max_pp: 20, tier: 3, min_level: 35 },
  { name: "Hardy Barrage", type: "universal", category: "physical", power: 80, accuracy: 100, max_pp: 17, tier: 3, min_level: 35 },
  { name: "Quick Slam", type: "universal", category: "special", power: 70, accuracy: 98, max_pp: 15, tier: 3, min_level: 35 },
  { name: "Primal Assault", type: "universal", category: "physical", power: 73, accuracy: 96, max_pp: 18, tier: 3, min_level: 35 },
  { name: "Bold Charge", type: "universal", category: "physical", power: 76, accuracy: 87, max_pp: 19, tier: 3, min_level: 35 },
  { name: "Bold Rush", type: "universal", category: "special", power: 75, accuracy: 98, max_pp: 15, tier: 3, min_level: 35 },
  { name: "Primal Uppercut", type: "universal", category: "physical", power: 79, accuracy: 86, max_pp: 15, tier: 3, min_level: 35 },
  { name: "Hardy Strike", type: "universal", category: "physical", power: 73, accuracy: 100, max_pp: 20, tier: 3, min_level: 35 },
  { name: "Quick Uppercut", type: "universal", category: "special", power: 75, accuracy: 100, max_pp: 19, tier: 3, min_level: 35 },
  { name: "Grit Strike", type: "universal", category: "physical", power: 78, accuracy: 90, max_pp: 17, tier: 3, min_level: 35 },
  { name: "Bold Pounce", type: "universal", category: "physical", power: 97, accuracy: 95, max_pp: 11, tier: 4, min_level: 55 },
  { name: "Rapid Barrage", type: "universal", category: "special", power: 92, accuracy: 95, max_pp: 15, tier: 4, min_level: 55 },
  { name: "Brave Uppercut", type: "universal", category: "physical", power: 93, accuracy: 90, max_pp: 12, tier: 4, min_level: 55 },
  { name: "Feral Strike", type: "universal", category: "physical", power: 102, accuracy: 82, max_pp: 13, tier: 4, min_level: 55 },
  { name: "Bold Guard", type: "universal", category: "status", power: 0, accuracy: 96, max_pp: 11, tier: 4, min_level: 55 },
  { name: "Grit Clash", type: "universal", category: "physical", power: 103, accuracy: 85, max_pp: 13, tier: 4, min_level: 55 },
  { name: "Wild Assault", type: "universal", category: "physical", power: 97, accuracy: 94, max_pp: 11, tier: 4, min_level: 55 },
  { name: "Iron Strike", type: "universal", category: "special", power: 91, accuracy: 91, max_pp: 14, tier: 4, min_level: 55 },
  { name: "Rapid Sweep", type: "universal", category: "physical", power: 94, accuracy: 94, max_pp: 15, tier: 4, min_level: 55 },
  { name: "Feral Dash", type: "universal", category: "physical", power: 100, accuracy: 85, max_pp: 13, tier: 4, min_level: 55 },
  { name: "Bold Barrage", type: "universal", category: "special", power: 118, accuracy: 88, max_pp: 6, tier: 5, min_level: 80 },
  { name: "True Rush", type: "universal", category: "physical", power: 124, accuracy: 90, max_pp: 10, tier: 5, min_level: 80 },
  { name: "True Clash", type: "universal", category: "physical", power: 116, accuracy: 78, max_pp: 7, tier: 5, min_level: 80 },
  { name: "Rapid Clash", type: "universal", category: "special", power: 129, accuracy: 74, max_pp: 10, tier: 5, min_level: 80 },
  { name: "Bold Bash", type: "universal", category: "physical", power: 117, accuracy: 80, max_pp: 9, tier: 5, min_level: 80 },
  { name: "Feral Slam", type: "universal", category: "physical", power: 115, accuracy: 77, max_pp: 7, tier: 5, min_level: 80 },
  { name: "Feral Uppercut", type: "universal", category: "special", power: 118, accuracy: 73, max_pp: 6, tier: 5, min_level: 80 },
  { name: "Bold Sweep", type: "universal", category: "physical", power: 113, accuracy: 76, max_pp: 8, tier: 5, min_level: 80 },
  { name: "Quick Bash", type: "universal", category: "physical", power: 114, accuracy: 79, max_pp: 10, tier: 5, min_level: 80 },
  { name: "Wild Pounce", type: "universal", category: "special", power: 118, accuracy: 76, max_pp: 5, tier: 5, min_level: 80 },
];

export function starterMoves(types: string[]): MoveJson[] {
  const pool: MoveJson[] = [];
  for (const type of types) {
    pool.push(...(BY_TYPE[type] ?? []).filter((m) => m.tier === 1));
  }
  pool.push(...UNIVERSAL_MOVES.filter((m) => m.tier === 1));
  if (types.length > 0) {
    pool.push(...(BY_TYPE[types[0]] ?? []).filter((m) => m.tier === 1));
  }
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const seen = new Set<string>();
  const result: MoveJson[] = [];
  for (const move of pool) {
    if (!seen.has(move.name)) { seen.add(move.name); result.push(move); }
    if (result.length === 4) break;
  }
  return result;
}
